[2021-10-05 09:11:26] I engine | Traceback (most recent call last):
  File "/home/ec2-user/environment/m1/app/core-service/core/engine.py", line 127, in wrapper
    return function(self, *args, **kwargs)
  File "/home/ec2-user/environment/m1/app/core-service/core/engine.py", line 149, in get_next_task
    return self.db.get_next_task()
  File "/home/ec2-user/environment/m1/app/core-service/core/dynamo.py", line 187, in get_next_task
    ReturnValues = 'ALL_OLD'
  File "/home/ec2-user/environment/flask-env/lib64/python3.7/site-packages/boto3/resources/factory.py", line 520, in do_action
    response = action(self, *args, **kwargs)
  File "/home/ec2-user/environment/flask-env/lib64/python3.7/site-packages/boto3/resources/action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(*args, **params)
  File "/home/ec2-user/environment/flask-env/lib64/python3.7/site-packages/botocore/client.py", line 386, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/ec2-user/environment/flask-env/lib64/python3.7/site-packages/botocore/client.py", line 705, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (ExpiredTokenException) when calling the UpdateItem operation: The security token included in the request is expired

[2021-10-05 09:11:27] I engine | Traceback (most recent call last):
  File "/home/ec2-user/environment/m1/app/core-service/core/engine.py", line 127, in wrapper
    return function(self, *args, **kwargs)
  File "/home/ec2-user/environment/m1/app/core-service/core/engine.py", line 149, in get_next_task
    return self.db.get_next_task()
  File "/home/ec2-user/environment/m1/app/core-service/core/dynamo.py", line 187, in get_next_task
    ReturnValues = 'ALL_OLD'
  File "/home/ec2-user/environment/flask-env/lib64/python3.7/site-packages/boto3/resources/factory.py", line 520, in do_action
    response = action(self, *args, **kwargs)
  File "/home/ec2-user/environment/flask-env/lib64/python3.7/site-packages/boto3/resources/action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(*args, **params)
  File "/home/ec2-user/environment/flask-env/lib64/python3.7/site-packages/botocore/client.py", line 386, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/ec2-user/environment/flask-env/lib64/python3.7/site-packages/botocore/client.py", line 705, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (ExpiredTokenException) when calling the UpdateItem operation: The security token included in the request is expired

[2021-10-05 09:11:28] I engine | Traceback (most recent call last):
  File "/home/ec2-user/environment/m1/app/core-service/core/engine.py", line 127, in wrapper
    return function(self, *args, **kwargs)
  File "/home/ec2-user/environment/m1/app/core-service/core/engine.py", line 149, in get_next_task
    return self.db.get_next_task()
  File "/home/ec2-user/environment/m1/app/core-service/core/dynamo.py", line 187, in get_next_task
    ReturnValues = 'ALL_OLD'
  File "/home/ec2-user/environment/flask-env/lib64/python3.7/site-packages/boto3/resources/factory.py", line 520, in do_action
    response = action(self, *args, **kwargs)
  File "/home/ec2-user/environment/flask-env/lib64/python3.7/site-packages/boto3/resources/action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(*args, **params)
  File "/home/ec2-user/environment/flask-env/lib64/python3.7/site-packages/botocore/client.py", line 386, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/ec2-user/environment/flask-env/lib64/python3.7/site-packages/botocore/client.py", line 705, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (ExpiredTokenException) when calling the UpdateItem operation: The security token included in the request is expired

[2021-10-05 09:11:29] I engine | Traceback (most recent call last):
  File "/home/ec2-user/environment/m1/app/core-service/core/engine.py", line 127, in wrapper
    return function(self, *args, **kwargs)
  File "/home/ec2-user/environment/m1/app/core-service/core/engine.py", line 149, in get_next_task
    return self.db.get_next_task()
  File "/home/ec2-user/environment/m1/app/core-service/core/dynamo.py", line 187, in get_next_task
    ReturnValues = 'ALL_OLD'
  File "/home/ec2-user/environment/flask-env/lib64/python3.7/site-packages/boto3/resources/factory.py", line 520, in do_action
    response = action(self, *args, **kwargs)
  File "/home/ec2-user/environment/flask-env/lib64/python3.7/site-packages/boto3/resources/action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(*args, **params)
  File "/home/ec2-user/environment/flask-env/lib64/python3.7/site-packages/botocore/client.py", line 386, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/ec2-user/environment/flask-env/lib64/python3.7/site-packages/botocore/client.py", line 705, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (ExpiredTokenException) when calling the UpdateItem operation: The security token included in the request is expired

[2021-10-05 09:11:30] I engine | Traceback (most recent call last):
  File "/home/ec2-user/environment/m1/app/core-service/core/engine.py", line 127, in wrapper
    return function(self, *args, **kwargs)
  File "/home/ec2-user/environment/m1/app/core-service/core/engine.py", line 149, in get_next_task
    return self.db.get_next_task()
  File "/home/ec2-user/environment/m1/app/core-service/core/dynamo.py", line 187, in get_next_task
    ReturnValues = 'ALL_OLD'
  File "/home/ec2-user/environment/flask-env/lib64/python3.7/site-packages/boto3/resources/factory.py", line 520, in do_action
    response = action(self, *args, **kwargs)
  File "/home/ec2-user/environment/flask-env/lib64/python3.7/site-packages/boto3/resources/action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(*args, **params)
  File "/home/ec2-user/environment/flask-env/lib64/python3.7/site-packages/botocore/client.py", line 386, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/ec2-user/environment/flask-env/lib64/python3.7/site-packages/botocore/client.py", line 705, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (ExpiredTokenException) when calling the UpdateItem operation: The security token included in the request is expired

[2021-10-05 09:11:31] I engine | Traceback (most recent call last):
  File "/home/ec2-user/environment/m1/app/core-service/core/engine.py", line 127, in wrapper
    return function(self, *args, **kwargs)
  File "/home/ec2-user/environment/m1/app/core-service/core/engine.py", line 149, in get_next_task
    return self.db.get_next_task()
  File "/home/ec2-user/environment/m1/app/core-service/core/dynamo.py", line 187, in get_next_task
    ReturnValues = 'ALL_OLD'
  File "/home/ec2-user/environment/flask-env/lib64/python3.7/site-packages/boto3/resources/factory.py", line 520, in do_action
    response = action(self, *args, **kwargs)
  File "/home/ec2-user/environment/flask-env/lib64/python3.7/site-packages/boto3/resources/action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(*args, **params)
  File "/home/ec2-user/environment/flask-env/lib64/python3.7/site-packages/botocore/client.py", line 386, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/ec2-user/environment/flask-env/lib64/python3.7/site-packages/botocore/client.py", line 705, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (ExpiredTokenException) when calling the UpdateItem operation: The security token included in the request is expired

[2021-10-05 09:11:32] I engine | Traceback (most recent call last):
  File "/home/ec2-user/environment/m1/app/core-service/core/engine.py", line 127, in wrapper
    return function(self, *args, **kwargs)
  File "/home/ec2-user/environment/m1/app/core-service/core/engine.py", line 149, in get_next_task
    return self.db.get_next_task()
  File "/home/ec2-user/environment/m1/app/core-service/core/dynamo.py", line 187, in get_next_task
    ReturnValues = 'ALL_OLD'
  File "/home/ec2-user/environment/flask-env/lib64/python3.7/site-packages/boto3/resources/factory.py", line 520, in do_action
    response = action(self, *args, **kwargs)
  File "/home/ec2-user/environment/flask-env/lib64/python3.7/site-packages/boto3/resources/action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(*args, **params)
  File "/home/ec2-user/environment/flask-env/lib64/python3.7/site-packages/botocore/client.py", line 386, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/ec2-user/environment/flask-env/lib64/python3.7/site-packages/botocore/client.py", line 705, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (ExpiredTokenException) when calling the UpdateItem operation: The security token included in the request is expired

[2021-10-05 09:11:33] I engine | Traceback (most recent call last):
  File "/home/ec2-user/environment/m1/app/core-service/core/engine.py", line 127, in wrapper
    return function(self, *args, **kwargs)
  File "/home/ec2-user/environment/m1/app/core-service/core/engine.py", line 149, in get_next_task
    return self.db.get_next_task()
  File "/home/ec2-user/environment/m1/app/core-service/core/dynamo.py", line 187, in get_next_task
    ReturnValues = 'ALL_OLD'
  File "/home/ec2-user/environment/flask-env/lib64/python3.7/site-packages/boto3/resources/factory.py", line 520, in do_action
    response = action(self, *args, **kwargs)
  File "/home/ec2-user/environment/flask-env/lib64/python3.7/site-packages/boto3/resources/action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(*args, **params)
  File "/home/ec2-user/environment/flask-env/lib64/python3.7/site-packages/botocore/client.py", line 386, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/ec2-user/environment/flask-env/lib64/python3.7/site-packages/botocore/client.py", line 705, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (ExpiredTokenException) when calling the UpdateItem operation: The security token included in the request is expired

[2021-10-05 09:11:34] I engine | Traceback (most recent call last):
  File "/home/ec2-user/environment/m1/app/core-service/core/engine.py", line 127, in wrapper
    return function(self, *args, **kwargs)
  File "/home/ec2-user/environment/m1/app/core-service/core/engine.py", line 149, in get_next_task
    return self.db.get_next_task()
  File "/home/ec2-user/environment/m1/app/core-service/core/dynamo.py", line 187, in get_next_task
    ReturnValues = 'ALL_OLD'
  File "/home/ec2-user/environment/flask-env/lib64/python3.7/site-packages/boto3/resources/factory.py", line 520, in do_action
    response = action(self, *args, **kwargs)
  File "/home/ec2-user/environment/flask-env/lib64/python3.7/site-packages/boto3/resources/action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(*args, **params)
  File "/home/ec2-user/environment/flask-env/lib64/python3.7/site-packages/botocore/client.py", line 386, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/ec2-user/environment/flask-env/lib64/python3.7/site-packages/botocore/client.py", line 705, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (ExpiredTokenException) when calling the UpdateItem operation: The security token included in the request is expired

[2021-10-05 09:11:35] I engine | Traceback (most recent call last):
  File "/home/ec2-user/environment/m1/app/core-service/core/engine.py", line 127, in wrapper
    return function(self, *args, **kwargs)
  File "/home/ec2-user/environment/m1/app/core-service/core/engine.py", line 149, in get_next_task
    return self.db.get_next_task()
  File "/home/ec2-user/environment/m1/app/core-service/core/dynamo.py", line 187, in get_next_task
    ReturnValues = 'ALL_OLD'
  File "/home/ec2-user/environment/flask-env/lib64/python3.7/site-packages/boto3/resources/factory.py", line 520, in do_action
    response = action(self, *args, **kwargs)
  File "/home/ec2-user/environment/flask-env/lib64/python3.7/site-packages/boto3/resources/action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(*args, **params)
  File "/home/ec2-user/environment/flask-env/lib64/python3.7/site-packages/botocore/client.py", line 386, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/ec2-user/environment/flask-env/lib64/python3.7/site-packages/botocore/client.py", line 705, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (ExpiredTokenException) when calling the UpdateItem operation: The security token included in the request is expired

[2021-10-05 09:11:36] I engine | Traceback (most recent call last):
  File "/home/ec2-user/environment/m1/app/core-service/core/engine.py", line 127, in wrapper
    return function(self, *args, **kwargs)
  File "/home/ec2-user/environment/m1/app/core-service/core/engine.py", line 149, in get_next_task
    return self.db.get_next_task()
  File "/home/ec2-user/environment/m1/app/core-service/core/dynamo.py", line 187, in get_next_task
    ReturnValues = 'ALL_OLD'
  File "/home/ec2-user/environment/flask-env/lib64/python3.7/site-packages/boto3/resources/factory.py", line 520, in do_action
    response = action(self, *args, **kwargs)
  File "/home/ec2-user/environment/flask-env/lib64/python3.7/site-packages/boto3/resources/action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(*args, **params)
  File "/home/ec2-user/environment/flask-env/lib64/python3.7/site-packages/botocore/client.py", line 386, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/ec2-user/environment/flask-env/lib64/python3.7/site-packages/botocore/client.py", line 705, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (ExpiredTokenException) when calling the UpdateItem operation: The security token included in the request is expired

[2021-10-05 09:11:37] I engine | Traceback (most recent call last):
  File "/home/ec2-user/environment/m1/app/core-service/core/engine.py", line 127, in wrapper
    return function(self, *args, **kwargs)
  File "/home/ec2-user/environment/m1/app/core-service/core/engine.py", line 149, in get_next_task
    return self.db.get_next_task()
  File "/home/ec2-user/environment/m1/app/core-service/core/dynamo.py", line 187, in get_next_task
    ReturnValues = 'ALL_OLD'
  File "/home/ec2-user/environment/flask-env/lib64/python3.7/site-packages/boto3/resources/factory.py", line 520, in do_action
    response = action(self, *args, **kwargs)
  File "/home/ec2-user/environment/flask-env/lib64/python3.7/site-packages/boto3/resources/action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(*args, **params)
  File "/home/ec2-user/environment/flask-env/lib64/python3.7/site-packages/botocore/client.py", line 386, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/ec2-user/environment/flask-env/lib64/python3.7/site-packages/botocore/client.py", line 705, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (ExpiredTokenException) when calling the UpdateItem operation: The security token included in the request is expired

[2021-10-05 09:11:38] I engine | Traceback (most recent call last):
  File "/home/ec2-user/environment/m1/app/core-service/core/engine.py", line 127, in wrapper
    return function(self, *args, **kwargs)
  File "/home/ec2-user/environment/m1/app/core-service/core/engine.py", line 149, in get_next_task
    return self.db.get_next_task()
  File "/home/ec2-user/environment/m1/app/core-service/core/dynamo.py", line 187, in get_next_task
    ReturnValues = 'ALL_OLD'
  File "/home/ec2-user/environment/flask-env/lib64/python3.7/site-packages/boto3/resources/factory.py", line 520, in do_action
    response = action(self, *args, **kwargs)
  File "/home/ec2-user/environment/flask-env/lib64/python3.7/site-packages/boto3/resources/action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(*args, **params)
  File "/home/ec2-user/environment/flask-env/lib64/python3.7/site-packages/botocore/client.py", line 386, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/ec2-user/environment/flask-env/lib64/python3.7/site-packages/botocore/client.py", line 705, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (ExpiredTokenException) when calling the UpdateItem operation: The security token included in the request is expired

[2021-10-05 09:11:39] I engine | Traceback (most recent call last):
  File "/home/ec2-user/environment/m1/app/core-service/core/engine.py", line 127, in wrapper
    return function(self, *args, **kwargs)
  File "/home/ec2-user/environment/m1/app/core-service/core/engine.py", line 149, in get_next_task
    return self.db.get_next_task()
  File "/home/ec2-user/environment/m1/app/core-service/core/dynamo.py", line 187, in get_next_task
    ReturnValues = 'ALL_OLD'
  File "/home/ec2-user/environment/flask-env/lib64/python3.7/site-packages/boto3/resources/factory.py", line 520, in do_action
    response = action(self, *args, **kwargs)
  File "/home/ec2-user/environment/flask-env/lib64/python3.7/site-packages/boto3/resources/action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(*args, **params)
  File "/home/ec2-user/environment/flask-env/lib64/python3.7/site-packages/botocore/client.py", line 386, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/ec2-user/environment/flask-env/lib64/python3.7/site-packages/botocore/client.py", line 705, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (ExpiredTokenException) when calling the UpdateItem operation: The security token included in the request is expired

[2021-10-05 09:11:40] I engine | Traceback (most recent call last):
  File "/home/ec2-user/environment/m1/app/core-service/core/engine.py", line 127, in wrapper
    return function(self, *args, **kwargs)
  File "/home/ec2-user/environment/m1/app/core-service/core/engine.py", line 149, in get_next_task
    return self.db.get_next_task()
  File "/home/ec2-user/environment/m1/app/core-service/core/dynamo.py", line 187, in get_next_task
    ReturnValues = 'ALL_OLD'
  File "/home/ec2-user/environment/flask-env/lib64/python3.7/site-packages/boto3/resources/factory.py", line 520, in do_action
    response = action(self, *args, **kwargs)
  File "/home/ec2-user/environment/flask-env/lib64/python3.7/site-packages/boto3/resources/action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(*args, **params)
  File "/home/ec2-user/environment/flask-env/lib64/python3.7/site-packages/botocore/client.py", line 386, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/ec2-user/environment/flask-env/lib64/python3.7/site-packages/botocore/client.py", line 705, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (ExpiredTokenException) when calling the UpdateItem operation: The security token included in the request is expired

[2021-10-05 09:11:41] I engine | Traceback (most recent call last):
  File "/home/ec2-user/environment/m1/app/core-service/core/engine.py", line 127, in wrapper
    return function(self, *args, **kwargs)
  File "/home/ec2-user/environment/m1/app/core-service/core/engine.py", line 149, in get_next_task
    return self.db.get_next_task()
  File "/home/ec2-user/environment/m1/app/core-service/core/dynamo.py", line 187, in get_next_task
    ReturnValues = 'ALL_OLD'
  File "/home/ec2-user/environment/flask-env/lib64/python3.7/site-packages/boto3/resources/factory.py", line 520, in do_action
    response = action(self, *args, **kwargs)
  File "/home/ec2-user/environment/flask-env/lib64/python3.7/site-packages/boto3/resources/action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(*args, **params)
  File "/home/ec2-user/environment/flask-env/lib64/python3.7/site-packages/botocore/client.py", line 386, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/ec2-user/environment/flask-env/lib64/python3.7/site-packages/botocore/client.py", line 705, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (ExpiredTokenException) when calling the UpdateItem operation: The security token included in the request is expired

[2021-10-05 09:11:42] I engine | Traceback (most recent call last):
  File "/home/ec2-user/environment/m1/app/core-service/core/engine.py", line 127, in wrapper
    return function(self, *args, **kwargs)
  File "/home/ec2-user/environment/m1/app/core-service/core/engine.py", line 149, in get_next_task
    return self.db.get_next_task()
  File "/home/ec2-user/environment/m1/app/core-service/core/dynamo.py", line 187, in get_next_task
    ReturnValues = 'ALL_OLD'
  File "/home/ec2-user/environment/flask-env/lib64/python3.7/site-packages/boto3/resources/factory.py", line 520, in do_action
    response = action(self, *args, **kwargs)
  File "/home/ec2-user/environment/flask-env/lib64/python3.7/site-packages/boto3/resources/action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(*args, **params)
  File "/home/ec2-user/environment/flask-env/lib64/python3.7/site-packages/botocore/client.py", line 386, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/ec2-user/environment/flask-env/lib64/python3.7/site-packages/botocore/client.py", line 705, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (ExpiredTokenException) when calling the UpdateItem operation: The security token included in the request is expired

[2021-10-05 09:11:43] I engine | Traceback (most recent call last):
  File "/home/ec2-user/environment/m1/app/core-service/core/engine.py", line 127, in wrapper
    return function(self, *args, **kwargs)
  File "/home/ec2-user/environment/m1/app/core-service/core/engine.py", line 149, in get_next_task
    return self.db.get_next_task()
  File "/home/ec2-user/environment/m1/app/core-service/core/dynamo.py", line 187, in get_next_task
    ReturnValues = 'ALL_OLD'
  File "/home/ec2-user/environment/flask-env/lib64/python3.7/site-packages/boto3/resources/factory.py", line 520, in do_action
    response = action(self, *args, **kwargs)
  File "/home/ec2-user/environment/flask-env/lib64/python3.7/site-packages/boto3/resources/action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(*args, **params)
  File "/home/ec2-user/environment/flask-env/lib64/python3.7/site-packages/botocore/client.py", line 386, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/ec2-user/environment/flask-env/lib64/python3.7/site-packages/botocore/client.py", line 705, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (ExpiredTokenException) when calling the UpdateItem operation: The security token included in the request is expired

[2021-10-05 09:11:44] I engine | Traceback (most recent call last):
  File "/home/ec2-user/environment/m1/app/core-service/core/engine.py", line 127, in wrapper
    return function(self, *args, **kwargs)
  File "/home/ec2-user/environment/m1/app/core-service/core/engine.py", line 149, in get_next_task
    return self.db.get_next_task()
  File "/home/ec2-user/environment/m1/app/core-service/core/dynamo.py", line 187, in get_next_task
    ReturnValues = 'ALL_OLD'
  File "/home/ec2-user/environment/flask-env/lib64/python3.7/site-packages/boto3/resources/factory.py", line 520, in do_action
    response = action(self, *args, **kwargs)
  File "/home/ec2-user/environment/flask-env/lib64/python3.7/site-packages/boto3/resources/action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(*args, **params)
  File "/home/ec2-user/environment/flask-env/lib64/python3.7/site-packages/botocore/client.py", line 386, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/ec2-user/environment/flask-env/lib64/python3.7/site-packages/botocore/client.py", line 705, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (ExpiredTokenException) when calling the UpdateItem operation: The security token included in the request is expired

[2021-10-05 09:11:45] I engine | Traceback (most recent call last):
  File "/home/ec2-user/environment/m1/app/core-service/core/engine.py", line 127, in wrapper
    return function(self, *args, **kwargs)
  File "/home/ec2-user/environment/m1/app/core-service/core/engine.py", line 149, in get_next_task
    return self.db.get_next_task()
  File "/home/ec2-user/environment/m1/app/core-service/core/dynamo.py", line 187, in get_next_task
    ReturnValues = 'ALL_OLD'
  File "/home/ec2-user/environment/flask-env/lib64/python3.7/site-packages/boto3/resources/factory.py", line 520, in do_action
    response = action(self, *args, **kwargs)
  File "/home/ec2-user/environment/flask-env/lib64/python3.7/site-packages/boto3/resources/action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(*args, **params)
  File "/home/ec2-user/environment/flask-env/lib64/python3.7/site-packages/botocore/client.py", line 386, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/ec2-user/environment/flask-env/lib64/python3.7/site-packages/botocore/client.py", line 705, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (ExpiredTokenException) when calling the UpdateItem operation: The security token included in the request is expired

[2021-10-05 09:11:46] I engine | Traceback (most recent call last):
  File "/home/ec2-user/environment/m1/app/core-service/core/engine.py", line 127, in wrapper
    return function(self, *args, **kwargs)
  File "/home/ec2-user/environment/m1/app/core-service/core/engine.py", line 149, in get_next_task
    return self.db.get_next_task()
  File "/home/ec2-user/environment/m1/app/core-service/core/dynamo.py", line 187, in get_next_task
    ReturnValues = 'ALL_OLD'
  File "/home/ec2-user/environment/flask-env/lib64/python3.7/site-packages/boto3/resources/factory.py", line 520, in do_action
    response = action(self, *args, **kwargs)
  File "/home/ec2-user/environment/flask-env/lib64/python3.7/site-packages/boto3/resources/action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(*args, **params)
  File "/home/ec2-user/environment/flask-env/lib64/python3.7/site-packages/botocore/client.py", line 386, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/ec2-user/environment/flask-env/lib64/python3.7/site-packages/botocore/client.py", line 705, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (ExpiredTokenException) when calling the UpdateItem operation: The security token included in the request is expired

[2021-10-05 09:11:47] I engine | Traceback (most recent call last):
  File "/home/ec2-user/environment/m1/app/core-service/core/engine.py", line 127, in wrapper
    return function(self, *args, **kwargs)
  File "/home/ec2-user/environment/m1/app/core-service/core/engine.py", line 149, in get_next_task
    return self.db.get_next_task()
  File "/home/ec2-user/environment/m1/app/core-service/core/dynamo.py", line 187, in get_next_task
    ReturnValues = 'ALL_OLD'
  File "/home/ec2-user/environment/flask-env/lib64/python3.7/site-packages/boto3/resources/factory.py", line 520, in do_action
    response = action(self, *args, **kwargs)
  File "/home/ec2-user/environment/flask-env/lib64/python3.7/site-packages/boto3/resources/action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(*args, **params)
  File "/home/ec2-user/environment/flask-env/lib64/python3.7/site-packages/botocore/client.py", line 386, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/ec2-user/environment/flask-env/lib64/python3.7/site-packages/botocore/client.py", line 705, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (ExpiredTokenException) when calling the UpdateItem operation: The security token included in the request is expired

[2021-10-05 09:11:48] I engine | Traceback (most recent call last):
  File "/home/ec2-user/environment/m1/app/core-service/core/engine.py", line 127, in wrapper
    return function(self, *args, **kwargs)
  File "/home/ec2-user/environment/m1/app/core-service/core/engine.py", line 149, in get_next_task
    return self.db.get_next_task()
  File "/home/ec2-user/environment/m1/app/core-service/core/dynamo.py", line 187, in get_next_task
    ReturnValues = 'ALL_OLD'
  File "/home/ec2-user/environment/flask-env/lib64/python3.7/site-packages/boto3/resources/factory.py", line 520, in do_action
    response = action(self, *args, **kwargs)
  File "/home/ec2-user/environment/flask-env/lib64/python3.7/site-packages/boto3/resources/action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(*args, **params)
  File "/home/ec2-user/environment/flask-env/lib64/python3.7/site-packages/botocore/client.py", line 386, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/ec2-user/environment/flask-env/lib64/python3.7/site-packages/botocore/client.py", line 705, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (ExpiredTokenException) when calling the UpdateItem operation: The security token included in the request is expired

[2021-10-05 09:11:49] I engine | Traceback (most recent call last):
  File "/home/ec2-user/environment/m1/app/core-service/core/engine.py", line 127, in wrapper
    return function(self, *args, **kwargs)
  File "/home/ec2-user/environment/m1/app/core-service/core/engine.py", line 149, in get_next_task
    return self.db.get_next_task()
  File "/home/ec2-user/environment/m1/app/core-service/core/dynamo.py", line 187, in get_next_task
    ReturnValues = 'ALL_OLD'
  File "/home/ec2-user/environment/flask-env/lib64/python3.7/site-packages/boto3/resources/factory.py", line 520, in do_action
    response = action(self, *args, **kwargs)
  File "/home/ec2-user/environment/flask-env/lib64/python3.7/site-packages/boto3/resources/action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(*args, **params)
  File "/home/ec2-user/environment/flask-env/lib64/python3.7/site-packages/botocore/client.py", line 386, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/ec2-user/environment/flask-env/lib64/python3.7/site-packages/botocore/client.py", line 705, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (ExpiredTokenException) when calling the UpdateItem operation: The security token included in the request is expired

[2021-10-05 09:11:51] I engine | Traceback (most recent call last):
  File "/home/ec2-user/environment/m1/app/core-service/core/engine.py", line 127, in wrapper
    return function(self, *args, **kwargs)
  File "/home/ec2-user/environment/m1/app/core-service/core/engine.py", line 149, in get_next_task
    return self.db.get_next_task()
  File "/home/ec2-user/environment/m1/app/core-service/core/dynamo.py", line 187, in get_next_task
    ReturnValues = 'ALL_OLD'
  File "/home/ec2-user/environment/flask-env/lib64/python3.7/site-packages/boto3/resources/factory.py", line 520, in do_action
    response = action(self, *args, **kwargs)
  File "/home/ec2-user/environment/flask-env/lib64/python3.7/site-packages/boto3/resources/action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(*args, **params)
  File "/home/ec2-user/environment/flask-env/lib64/python3.7/site-packages/botocore/client.py", line 386, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/ec2-user/environment/flask-env/lib64/python3.7/site-packages/botocore/client.py", line 705, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (ExpiredTokenException) when calling the UpdateItem operation: The security token included in the request is expired

[2021-10-05 09:11:52] I engine | Traceback (most recent call last):
  File "/home/ec2-user/environment/m1/app/core-service/core/engine.py", line 127, in wrapper
    return function(self, *args, **kwargs)
  File "/home/ec2-user/environment/m1/app/core-service/core/engine.py", line 149, in get_next_task
    return self.db.get_next_task()
  File "/home/ec2-user/environment/m1/app/core-service/core/dynamo.py", line 187, in get_next_task
    ReturnValues = 'ALL_OLD'
  File "/home/ec2-user/environment/flask-env/lib64/python3.7/site-packages/boto3/resources/factory.py", line 520, in do_action
    response = action(self, *args, **kwargs)
  File "/home/ec2-user/environment/flask-env/lib64/python3.7/site-packages/boto3/resources/action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(*args, **params)
  File "/home/ec2-user/environment/flask-env/lib64/python3.7/site-packages/botocore/client.py", line 386, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/ec2-user/environment/flask-env/lib64/python3.7/site-packages/botocore/client.py", line 705, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (ExpiredTokenException) when calling the UpdateItem operation: The security token included in the request is expired

[2021-10-05 09:11:53] I engine | Traceback (most recent call last):
  File "/home/ec2-user/environment/m1/app/core-service/core/engine.py", line 127, in wrapper
    return function(self, *args, **kwargs)
  File "/home/ec2-user/environment/m1/app/core-service/core/engine.py", line 149, in get_next_task
    return self.db.get_next_task()
  File "/home/ec2-user/environment/m1/app/core-service/core/dynamo.py", line 187, in get_next_task
    ReturnValues = 'ALL_OLD'
  File "/home/ec2-user/environment/flask-env/lib64/python3.7/site-packages/boto3/resources/factory.py", line 520, in do_action
    response = action(self, *args, **kwargs)
  File "/home/ec2-user/environment/flask-env/lib64/python3.7/site-packages/boto3/resources/action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(*args, **params)
  File "/home/ec2-user/environment/flask-env/lib64/python3.7/site-packages/botocore/client.py", line 386, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/ec2-user/environment/flask-env/lib64/python3.7/site-packages/botocore/client.py", line 705, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (ExpiredTokenException) when calling the UpdateItem operation: The security token included in the request is expired

[2021-10-05 09:11:54] I engine | Traceback (most recent call last):
  File "/home/ec2-user/environment/m1/app/core-service/core/engine.py", line 127, in wrapper
    return function(self, *args, **kwargs)
  File "/home/ec2-user/environment/m1/app/core-service/core/engine.py", line 149, in get_next_task
    return self.db.get_next_task()
  File "/home/ec2-user/environment/m1/app/core-service/core/dynamo.py", line 187, in get_next_task
    ReturnValues = 'ALL_OLD'
  File "/home/ec2-user/environment/flask-env/lib64/python3.7/site-packages/boto3/resources/factory.py", line 520, in do_action
    response = action(self, *args, **kwargs)
  File "/home/ec2-user/environment/flask-env/lib64/python3.7/site-packages/boto3/resources/action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(*args, **params)
  File "/home/ec2-user/environment/flask-env/lib64/python3.7/site-packages/botocore/client.py", line 386, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/ec2-user/environment/flask-env/lib64/python3.7/site-packages/botocore/client.py", line 705, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (ExpiredTokenException) when calling the UpdateItem operation: The security token included in the request is expired

[2021-10-05 09:11:55] I engine | Traceback (most recent call last):
  File "/home/ec2-user/environment/m1/app/core-service/core/engine.py", line 127, in wrapper
    return function(self, *args, **kwargs)
  File "/home/ec2-user/environment/m1/app/core-service/core/engine.py", line 149, in get_next_task
    return self.db.get_next_task()
  File "/home/ec2-user/environment/m1/app/core-service/core/dynamo.py", line 187, in get_next_task
    ReturnValues = 'ALL_OLD'
  File "/home/ec2-user/environment/flask-env/lib64/python3.7/site-packages/boto3/resources/factory.py", line 520, in do_action
    response = action(self, *args, **kwargs)
  File "/home/ec2-user/environment/flask-env/lib64/python3.7/site-packages/boto3/resources/action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(*args, **params)
  File "/home/ec2-user/environment/flask-env/lib64/python3.7/site-packages/botocore/client.py", line 386, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/ec2-user/environment/flask-env/lib64/python3.7/site-packages/botocore/client.py", line 705, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (ExpiredTokenException) when calling the UpdateItem operation: The security token included in the request is expired

[2021-10-05 09:11:56] I engine | Traceback (most recent call last):
  File "/home/ec2-user/environment/m1/app/core-service/core/engine.py", line 127, in wrapper
    return function(self, *args, **kwargs)
  File "/home/ec2-user/environment/m1/app/core-service/core/engine.py", line 149, in get_next_task
    return self.db.get_next_task()
  File "/home/ec2-user/environment/m1/app/core-service/core/dynamo.py", line 187, in get_next_task
    ReturnValues = 'ALL_OLD'
  File "/home/ec2-user/environment/flask-env/lib64/python3.7/site-packages/boto3/resources/factory.py", line 520, in do_action
    response = action(self, *args, **kwargs)
  File "/home/ec2-user/environment/flask-env/lib64/python3.7/site-packages/boto3/resources/action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(*args, **params)
  File "/home/ec2-user/environment/flask-env/lib64/python3.7/site-packages/botocore/client.py", line 386, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/ec2-user/environment/flask-env/lib64/python3.7/site-packages/botocore/client.py", line 705, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (ExpiredTokenException) when calling the UpdateItem operation: The security token included in the request is expired

[2021-10-05 09:11:57] I engine | Traceback (most recent call last):
  File "/home/ec2-user/environment/m1/app/core-service/core/engine.py", line 127, in wrapper
    return function(self, *args, **kwargs)
  File "/home/ec2-user/environment/m1/app/core-service/core/engine.py", line 149, in get_next_task
    return self.db.get_next_task()
  File "/home/ec2-user/environment/m1/app/core-service/core/dynamo.py", line 187, in get_next_task
    ReturnValues = 'ALL_OLD'
  File "/home/ec2-user/environment/flask-env/lib64/python3.7/site-packages/boto3/resources/factory.py", line 520, in do_action
    response = action(self, *args, **kwargs)
  File "/home/ec2-user/environment/flask-env/lib64/python3.7/site-packages/boto3/resources/action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(*args, **params)
  File "/home/ec2-user/environment/flask-env/lib64/python3.7/site-packages/botocore/client.py", line 386, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/ec2-user/environment/flask-env/lib64/python3.7/site-packages/botocore/client.py", line 705, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (ExpiredTokenException) when calling the UpdateItem operation: The security token included in the request is expired

[2021-10-05 09:11:57] I engine | Traceback (most recent call last):
  File "/home/ec2-user/environment/m1/app/core-service/core/engine.py", line 127, in wrapper
    return function(self, *args, **kwargs)
  File "/home/ec2-user/environment/m1/app/core-service/core/engine.py", line 159, in queue_worker
    time.sleep(1)
  File "/home/ec2-user/environment/m1/app/core-service/core/__init__.py", line 68, in termination_handler
AttributeError: 'FlaskApp' object has no attribute 'app'

[2021-10-05 09:12:04] I dynamo | DYNAMO initiated
[2021-10-05 09:12:06] I engine | RUNNER initiated: <core.engine.Runner object at 0x7f1d83ed7950>
[2021-10-05 09:12:07] I engine | RUNNER queue_worker started: 15193
[2021-10-05 09:12:07] I engine | RUNNER started: <core.engine.Runner object at 0x7f1d83ed7950>
[2021-10-05 09:12:07] I telegr | BOT initiated: <core.telegram.Bot object at 0x7f1d82a5ab10>
[2021-10-05 09:12:07] I telegr | BOT polling: <core.telegram.Bot object at 0x7f1d82a5ab10>
[2021-10-05 09:12:07] I telegr | BOT enumerate_threads: [<_MainThread(MainThread, started 139765594928960)>, <Thread(QueueManagerThread, started daemon 139764722173696)>, <Thread(Telegram bot polling, started daemon 139764705388288)>, <Thread(QueueFeederThread, initial daemon)>]
[2021-10-05 09:12:07] I cognit | COGNITO self.client_id: 27k0oc5jiv5m28l2ldre8c79f3
[2021-10-05 09:12:07] I cognit | COGNITO self.user_pool_id: us-east-1_Vzc2ve15D
[2021-10-05 09:12:07] I cognit | COGNITO self.domain: m1.ogoro.me
[2021-10-05 09:12:07] I cognit | COGNITO self.aws_nlb: m1-core-nlb-d1a3c13eaba292ca.elb.us-east-1.amazonaws.com
[2021-10-05 09:12:07] I cognit | COGNITO initiated: <core.cognito.Users object at 0x7f1d829f0490>
[2021-10-05 09:12:07] I facebo | FB self.domain: m1.ogoro.me
[2021-10-05 09:12:07] I facebo | FB self.aws_nlb: m1-core-nlb-d1a3c13eaba292ca.elb.us-east-1.amazonaws.com
[2021-10-05 09:12:07] I facebo | FB initiated: <core.facebook.FB object at 0x7f1d829f04d0>
[2021-10-05 09:12:29] I dynamo | DYNAMO initiated
[2021-10-05 09:12:32] I engine | RUNNER initiated: <core.engine.Runner object at 0x7f5751ca8ad0>
[2021-10-05 09:12:32] I engine | RUNNER queue_worker started: 15599
[2021-10-05 09:12:32] I engine | RUNNER started: <core.engine.Runner object at 0x7f5751ca8ad0>
[2021-10-05 09:12:32] I telegr | BOT initiated: <core.telegram.Bot object at 0x7f575082c790>
[2021-10-05 09:12:32] I telegr | BOT polling: <core.telegram.Bot object at 0x7f575082c790>
[2021-10-05 09:12:32] I telegr | BOT enumerate_threads: [<_MainThread(MainThread, started 140013861963584)>, <Thread(QueueManagerThread, started daemon 140012989134592)>, <Thread(Telegram bot polling, started daemon 140012972349184)>, <Thread(QueueFeederThread, initial daemon)>]
[2021-10-05 09:12:32] I cognit | COGNITO self.client_id: 27k0oc5jiv5m28l2ldre8c79f3
[2021-10-05 09:12:32] I cognit | COGNITO self.user_pool_id: us-east-1_Vzc2ve15D
[2021-10-05 09:12:32] I cognit | COGNITO self.domain: m1.ogoro.me
[2021-10-05 09:12:32] I cognit | COGNITO self.aws_nlb: m1-core-nlb-d1a3c13eaba292ca.elb.us-east-1.amazonaws.com
[2021-10-05 09:12:32] I cognit | COGNITO initiated: <core.cognito.Users object at 0x7f57507c1150>
[2021-10-05 09:12:32] I facebo | FB self.domain: m1.ogoro.me
[2021-10-05 09:12:32] I facebo | FB self.aws_nlb: m1-core-nlb-d1a3c13eaba292ca.elb.us-east-1.amazonaws.com
[2021-10-05 09:12:32] I facebo | FB initiated: <core.facebook.FB object at 0x7f57507c1190>
[2021-10-05 09:13:08] I engine | Traceback (most recent call last):
  File "/home/ec2-user/environment/m1/app/core-service/core/engine.py", line 127, in wrapper
    return function(self, *args, **kwargs)
  File "/home/ec2-user/environment/m1/app/core-service/core/engine.py", line 159, in queue_worker
    time.sleep(1)
  File "/home/ec2-user/environment/m1/app/core-service/core/app.py", line 68, in termination_handler
    config.clear_figures_folder(self.app)
AttributeError: 'FlaskApp' object has no attribute 'app'

[2021-10-05 09:13:14] I dynamo | DYNAMO initiated
[2021-10-05 09:13:17] I engine | RUNNER initiated: <core.engine.Runner object at 0x7f05da04d890>
[2021-10-05 09:13:17] I engine | RUNNER started: <core.engine.Runner object at 0x7f05da04d890>
[2021-10-05 09:13:17] I telegr | BOT initiated: <core.telegram.Bot object at 0x7f05d912e750>
[2021-10-05 09:13:17] I engine | RUNNER queue_worker started: 15989
[2021-10-05 09:13:17] I telegr | BOT polling: <core.telegram.Bot object at 0x7f05d912e750>
[2021-10-05 09:13:17] I telegr | BOT enumerate_threads: [<_MainThread(MainThread, started 139663965787968)>, <Thread(QueueManagerThread, started daemon 139663092958976)>, <Thread(Telegram bot polling, started daemon 139663008331520)>, <Thread(QueueFeederThread, initial daemon)>]
[2021-10-05 09:13:17] I cognit | COGNITO self.client_id: 27k0oc5jiv5m28l2ldre8c79f3
[2021-10-05 09:13:17] I cognit | COGNITO self.user_pool_id: us-east-1_Vzc2ve15D
[2021-10-05 09:13:17] I cognit | COGNITO self.domain: m1.ogoro.me
[2021-10-05 09:13:17] I cognit | COGNITO self.aws_nlb: m1-core-nlb-d1a3c13eaba292ca.elb.us-east-1.amazonaws.com
[2021-10-05 09:13:17] I cognit | COGNITO initiated: <core.cognito.Users object at 0x7f05d90c4150>
[2021-10-05 09:13:17] I facebo | FB self.domain: m1.ogoro.me
[2021-10-05 09:13:17] I facebo | FB self.aws_nlb: m1-core-nlb-d1a3c13eaba292ca.elb.us-east-1.amazonaws.com
[2021-10-05 09:13:17] I facebo | FB initiated: <core.facebook.FB object at 0x7f05d90c4190>
[2021-10-05 09:13:47] I engine | Traceback (most recent call last):
  File "/home/ec2-user/environment/m1/app/core-service/core/engine.py", line 127, in wrapper
    return function(self, *args, **kwargs)
  File "/home/ec2-user/environment/m1/app/core-service/core/engine.py", line 159, in queue_worker
    time.sleep(1)
  File "/home/ec2-user/environment/m1/app/core-service/core/app.py", line 68, in termination_handler
    config.clear_figures_folder(self.app)
AttributeError: 'FlaskApp' object has no attribute 'app'

[2021-10-05 09:13:52] I dynamo | DYNAMO initiated
[2021-10-05 09:13:54] I engine | RUNNER initiated: <core.engine.Runner object at 0x7f3235f96450>
[2021-10-05 09:13:54] I engine | RUNNER started: <core.engine.Runner object at 0x7f3235f96450>
[2021-10-05 09:13:54] I telegr | BOT initiated: <core.telegram.Bot object at 0x7f3235f07b50>
[2021-10-05 09:13:54] I engine | RUNNER queue_worker started: 16334
[2021-10-05 09:13:54] I telegr | BOT polling: <core.telegram.Bot object at 0x7f3235f07b50>
[2021-10-05 09:13:54] I telegr | BOT enumerate_threads: [<_MainThread(MainThread, started 139854502377280)>, <Thread(QueueManagerThread, started daemon 139853629548288)>, <Thread(Telegram bot polling, started daemon 139853612762880)>, <Thread(QueueFeederThread, initial daemon)>]
[2021-10-05 09:13:54] I cognit | COGNITO self.client_id: 27k0oc5jiv5m28l2ldre8c79f3
[2021-10-05 09:13:54] I cognit | COGNITO self.user_pool_id: us-east-1_Vzc2ve15D
[2021-10-05 09:13:54] I cognit | COGNITO self.domain: m1.ogoro.me
[2021-10-05 09:13:54] I cognit | COGNITO self.aws_nlb: m1-core-nlb-d1a3c13eaba292ca.elb.us-east-1.amazonaws.com
[2021-10-05 09:13:54] I cognit | COGNITO initiated: <core.cognito.Users object at 0x7f3235e9d510>
[2021-10-05 09:13:54] I facebo | FB self.domain: m1.ogoro.me
[2021-10-05 09:13:54] I facebo | FB self.aws_nlb: m1-core-nlb-d1a3c13eaba292ca.elb.us-east-1.amazonaws.com
[2021-10-05 09:13:54] I facebo | FB initiated: <core.facebook.FB object at 0x7f3235e9d550>
[2021-10-05 09:14:23] I engine | Traceback (most recent call last):
  File "/home/ec2-user/environment/m1/app/core-service/core/engine.py", line 127, in wrapper
    return function(self, *args, **kwargs)
  File "/home/ec2-user/environment/m1/app/core-service/core/engine.py", line 159, in queue_worker
    time.sleep(1)
  File "/home/ec2-user/environment/m1/app/core-service/core/app.py", line 68, in termination_handler
AttributeError: 'FlaskApp' object has no attribute 'app'

[2021-10-05 09:14:29] I dynamo | DYNAMO initiated
[2021-10-05 09:14:31] I engine | RUNNER initiated: <core.engine.Runner object at 0x7fc023e33d90>
[2021-10-05 09:14:31] I engine | RUNNER started: <core.engine.Runner object at 0x7fc023e33d90>
[2021-10-05 09:14:31] I telegr | BOT initiated: <core.telegram.Bot object at 0x7fc023d5bc10>
[2021-10-05 09:14:31] I engine | RUNNER queue_worker started: 16735
[2021-10-05 09:14:31] I telegr | BOT polling: <core.telegram.Bot object at 0x7fc023d5bc10>
[2021-10-05 09:14:31] I telegr | BOT enumerate_threads: [<_MainThread(MainThread, started 140464083871552)>, <Thread(QueueManagerThread, started daemon 140463211165440)>, <Thread(Telegram bot polling, started daemon 140463194380032)>, <Thread(QueueFeederThread, initial daemon)>]
[2021-10-05 09:14:31] I cognit | COGNITO self.client_id: 27k0oc5jiv5m28l2ldre8c79f3
[2021-10-05 09:14:31] I cognit | COGNITO self.user_pool_id: us-east-1_Vzc2ve15D
[2021-10-05 09:14:31] I cognit | COGNITO self.domain: m1.ogoro.me
[2021-10-05 09:14:31] I cognit | COGNITO self.aws_nlb: m1-core-nlb-d1a3c13eaba292ca.elb.us-east-1.amazonaws.com
[2021-10-05 09:14:31] I cognit | COGNITO initiated: <core.cognito.Users object at 0x7fc03352e510>
[2021-10-05 09:14:31] I facebo | FB self.domain: m1.ogoro.me
[2021-10-05 09:14:31] I facebo | FB self.aws_nlb: m1-core-nlb-d1a3c13eaba292ca.elb.us-east-1.amazonaws.com
[2021-10-05 09:14:31] I facebo | FB initiated: <core.facebook.FB object at 0x7fc023cf5690>
[2021-10-05 09:14:51] I engine | Traceback (most recent call last):
  File "/home/ec2-user/environment/m1/app/core-service/core/engine.py", line 127, in wrapper
    return function(self, *args, **kwargs)
  File "/home/ec2-user/environment/m1/app/core-service/core/engine.py", line 159, in queue_worker
    time.sleep(1)
  File "/home/ec2-user/environment/m1/app/core-service/core/app.py", line 65, in termination_handler
    config.clear_figures_folder(self.app)
AttributeError: 'FlaskApp' object has no attribute 'app'

[2021-10-05 09:15:15] I dynamo | DYNAMO initiated
[2021-10-05 09:15:17] I engine | RUNNER initiated: <core.engine.Runner object at 0x7f6f15869190>
[2021-10-05 09:15:17] I engine | RUNNER queue_worker started: 17104
[2021-10-05 09:15:17] I engine | RUNNER started: <core.engine.Runner object at 0x7f6f15869190>
[2021-10-05 09:15:17] I telegr | BOT initiated: <core.telegram.Bot object at 0x7f6f14947c90>
[2021-10-05 09:15:17] I telegr | BOT polling: <core.telegram.Bot object at 0x7f6f14947c90>
[2021-10-05 09:15:17] I telegr | BOT enumerate_threads: [<_MainThread(MainThread, started 140115935639360)>, <Thread(QueueManagerThread, started daemon 140115062884096)>, <Thread(Telegram bot polling, started daemon 140114978137856)>, <Thread(QueueFeederThread, initial daemon)>]
[2021-10-05 09:15:17] I cognit | COGNITO self.client_id: 27k0oc5jiv5m28l2ldre8c79f3
[2021-10-05 09:15:17] I cognit | COGNITO self.user_pool_id: us-east-1_Vzc2ve15D
[2021-10-05 09:15:17] I cognit | COGNITO self.domain: m1.ogoro.me
[2021-10-05 09:15:17] I cognit | COGNITO self.aws_nlb: m1-core-nlb-d1a3c13eaba292ca.elb.us-east-1.amazonaws.com
[2021-10-05 09:15:17] I cognit | COGNITO initiated: <core.cognito.Users object at 0x7f6f148de690>
[2021-10-05 09:15:17] I facebo | FB self.domain: m1.ogoro.me
[2021-10-05 09:15:17] I facebo | FB self.aws_nlb: m1-core-nlb-d1a3c13eaba292ca.elb.us-east-1.amazonaws.com
[2021-10-05 09:15:17] I facebo | FB initiated: <core.facebook.FB object at 0x7f6f148de6d0>
[2021-10-05 09:15:25] I engine | Traceback (most recent call last):
  File "/home/ec2-user/environment/m1/app/core-service/core/engine.py", line 127, in wrapper
    return function(self, *args, **kwargs)
  File "/home/ec2-user/environment/m1/app/core-service/core/engine.py", line 159, in queue_worker
    time.sleep(1)
  File "/home/ec2-user/environment/m1/app/core-service/core/app.py", line 65, in termination_handler
    config.clear_figures_folder(self.app)
AttributeError: 'FlaskApp' object has no attribute 'app'

[2021-10-05 09:15:50] I dynamo | DYNAMO initiated
[2021-10-05 09:15:52] I engine | RUNNER initiated: <core.engine.Runner object at 0x7f78da9e8a90>
[2021-10-05 09:15:52] I engine | RUNNER started: <core.engine.Runner object at 0x7f78da9e8a90>
[2021-10-05 09:15:52] I telegr | BOT initiated: <core.telegram.Bot object at 0x7f78da57d850>
[2021-10-05 09:15:52] I engine | RUNNER queue_worker started: 17455
[2021-10-05 09:15:52] I telegr | BOT polling: <core.telegram.Bot object at 0x7f78da57d850>
[2021-10-05 09:15:52] I telegr | BOT enumerate_threads: [<_MainThread(MainThread, started 140157908264768)>, <Thread(QueueManagerThread, started daemon 140157035484928)>, <Thread(Telegram bot polling, started daemon 140157018699520)>, <Thread(QueueFeederThread, initial daemon)>]
[2021-10-05 09:15:52] I cognit | COGNITO self.client_id: 27k0oc5jiv5m28l2ldre8c79f3
[2021-10-05 09:15:52] I cognit | COGNITO self.user_pool_id: us-east-1_Vzc2ve15D
[2021-10-05 09:15:52] I cognit | COGNITO self.domain: m1.ogoro.me
[2021-10-05 09:15:52] I cognit | COGNITO self.aws_nlb: m1-core-nlb-d1a3c13eaba292ca.elb.us-east-1.amazonaws.com
[2021-10-05 09:15:52] I cognit | COGNITO initiated: <core.cognito.Users object at 0x7f78da510250>
[2021-10-05 09:15:52] I facebo | FB self.domain: m1.ogoro.me
[2021-10-05 09:15:52] I facebo | FB self.aws_nlb: m1-core-nlb-d1a3c13eaba292ca.elb.us-east-1.amazonaws.com
[2021-10-05 09:15:52] I facebo | FB initiated: <core.facebook.FB object at 0x7f78da510290>
[2021-10-05 09:17:45] I dynamo | DYNAMO initiated
[2021-10-05 09:17:47] I engine | RUNNER initiated: <core.engine.Runner object at 0x7fc97bb4c810>
[2021-10-05 09:17:48] I engine | RUNNER queue_worker started: 18022
[2021-10-05 09:17:48] I engine | RUNNER started: <core.engine.Runner object at 0x7fc97bb4c810>
[2021-10-05 09:17:48] I telegr | BOT initiated: <core.telegram.Bot object at 0x7fc97a6e2e10>
[2021-10-05 09:17:48] I telegr | BOT polling: <core.telegram.Bot object at 0x7fc97a6e2e10>
[2021-10-05 09:17:48] I telegr | BOT enumerate_threads: [<_MainThread(MainThread, started 140504191477568)>, <Thread(QueueManagerThread, started daemon 140503318697728)>, <Thread(Telegram bot polling, started daemon 140503301912320)>, <Thread(QueueFeederThread, initial daemon)>]
[2021-10-05 09:17:48] I cognit | COGNITO self.client_id: 27k0oc5jiv5m28l2ldre8c79f3
[2021-10-05 09:17:48] I cognit | COGNITO self.user_pool_id: us-east-1_Vzc2ve15D
[2021-10-05 09:17:48] I cognit | COGNITO self.domain: m1.ogoro.me
[2021-10-05 09:17:48] I cognit | COGNITO self.aws_nlb: m1-core-nlb-d1a3c13eaba292ca.elb.us-east-1.amazonaws.com
[2021-10-05 09:17:48] I cognit | COGNITO initiated: <core.cognito.Users object at 0x7fc97a676790>
[2021-10-05 09:17:48] I facebo | FB self.domain: m1.ogoro.me
[2021-10-05 09:17:48] I facebo | FB self.aws_nlb: m1-core-nlb-d1a3c13eaba292ca.elb.us-east-1.amazonaws.com
[2021-10-05 09:17:48] I facebo | FB initiated: <core.facebook.FB object at 0x7fc97a6767d0>
[2021-10-05 09:17:58] I engine | Traceback (most recent call last):
  File "/home/ec2-user/environment/m1/app/core-service/core/engine.py", line 127, in wrapper
    return function(self, *args, **kwargs)
  File "/home/ec2-user/environment/m1/app/core-service/core/engine.py", line 159, in queue_worker
    time.sleep(1)
  File "/home/ec2-user/environment/m1/app/core-service/core/app.py", line 64, in termination_handler
    print(f'APP termination_handler signal {signal}, {frame}')
  File "/home/ec2-user/environment/m1/app/core-service/core/app.py", line 64, in termination_handler
    print(f'APP termination_handler signal {signal}, {frame}')
RuntimeError: reentrant call inside <_io.BufferedWriter name='<stdout>'>

[2021-10-05 09:19:16] I dynamo | DYNAMO initiated
[2021-10-05 09:19:18] I engine | RUNNER initiated: <core.engine.Runner object at 0x7f524f327d50>
[2021-10-05 09:19:18] I engine | RUNNER started: <core.engine.Runner object at 0x7f524f327d50>
[2021-10-05 09:19:18] I telegr | BOT initiated: <core.telegram.Bot object at 0x7f524f252ad0>
[2021-10-05 09:19:18] I engine | RUNNER queue_worker started: 18495
[2021-10-05 09:19:18] I telegr | BOT polling: <core.telegram.Bot object at 0x7f524f252ad0>
[2021-10-05 09:19:18] I telegr | BOT enumerate_threads: [<_MainThread(MainThread, started 139992364164928)>, <Thread(QueueManagerThread, started daemon 139991491385088)>, <Thread(Telegram bot polling, started daemon 139991474599680)>, <Thread(QueueFeederThread, initial daemon)>]
[2021-10-05 09:19:18] I cognit | COGNITO self.client_id: 27k0oc5jiv5m28l2ldre8c79f3
[2021-10-05 09:19:18] I cognit | COGNITO self.user_pool_id: us-east-1_Vzc2ve15D
[2021-10-05 09:19:18] I cognit | COGNITO self.domain: m1.ogoro.me
[2021-10-05 09:19:18] I cognit | COGNITO self.aws_nlb: m1-core-nlb-d1a3c13eaba292ca.elb.us-east-1.amazonaws.com
[2021-10-05 09:19:18] I cognit | COGNITO initiated: <core.cognito.Users object at 0x7f524f511b50>
[2021-10-05 09:19:18] I facebo | FB self.domain: m1.ogoro.me
[2021-10-05 09:19:18] I facebo | FB self.aws_nlb: m1-core-nlb-d1a3c13eaba292ca.elb.us-east-1.amazonaws.com
[2021-10-05 09:19:18] I facebo | FB initiated: <core.facebook.FB object at 0x7f524f1e94d0>
[2021-10-05 09:21:19] I dynamo | DYNAMO initiated
[2021-10-05 09:21:21] I engine | RUNNER initiated: <core.engine.Runner object at 0x7ff846328550>
[2021-10-05 09:21:21] I engine | RUNNER queue_worker started: 18986
[2021-10-05 09:21:21] I engine | RUNNER started: <core.engine.Runner object at 0x7ff846328550>
[2021-10-05 09:21:21] I telegr | BOT initiated: <core.telegram.Bot object at 0x7ff84540b950>
[2021-10-05 09:21:21] I telegr | BOT polling: <core.telegram.Bot object at 0x7ff84540b950>
[2021-10-05 09:21:21] I telegr | BOT enumerate_threads: [<_MainThread(MainThread, started 140705162733376)>, <Thread(QueueManagerThread, started daemon 140704289978112)>, <Thread(QueueFeederThread, started daemon 140704281585408)>, <Thread(Telegram bot polling, started daemon 140704202356480)>]
[2021-10-05 09:21:21] I cognit | COGNITO self.client_id: 27k0oc5jiv5m28l2ldre8c79f3
[2021-10-05 09:21:21] I cognit | COGNITO self.user_pool_id: us-east-1_Vzc2ve15D
[2021-10-05 09:21:21] I cognit | COGNITO self.domain: m1.ogoro.me
[2021-10-05 09:21:21] I cognit | COGNITO self.aws_nlb: m1-core-nlb-d1a3c13eaba292ca.elb.us-east-1.amazonaws.com
[2021-10-05 09:21:21] I cognit | COGNITO initiated: <core.cognito.Users object at 0x7ff8453a25d0>
[2021-10-05 09:21:21] I facebo | FB self.domain: m1.ogoro.me
[2021-10-05 09:21:21] I facebo | FB self.aws_nlb: m1-core-nlb-d1a3c13eaba292ca.elb.us-east-1.amazonaws.com
[2021-10-05 09:21:21] I facebo | FB initiated: <core.facebook.FB object at 0x7ff8454ef610>
[2021-10-05 09:22:12] I dynamo | DYNAMO initiated
[2021-10-05 09:22:15] I engine | RUNNER initiated: <core.engine.Runner object at 0x7f6dba1f4290>
[2021-10-05 09:22:15] I engine | RUNNER queue_worker started: 19384
[2021-10-05 09:22:15] I engine | RUNNER started: <core.engine.Runner object at 0x7f6dba1f4290>
[2021-10-05 09:22:15] I telegr | BOT initiated: <core.telegram.Bot object at 0x7f6db8adfa90>
[2021-10-05 09:22:15] I telegr | BOT polling: <core.telegram.Bot object at 0x7f6db8adfa90>
[2021-10-05 09:22:15] I telegr | BOT enumerate_threads: [<_MainThread(MainThread, started 140110098806592)>, <Thread(QueueManagerThread, started daemon 140109226075904)>, <Thread(Telegram bot polling, started daemon 140109139666688)>, <Thread(QueueFeederThread, initial daemon)>]
[2021-10-05 09:22:15] I cognit | COGNITO self.client_id: 27k0oc5jiv5m28l2ldre8c79f3
[2021-10-05 09:22:15] I cognit | COGNITO self.user_pool_id: us-east-1_Vzc2ve15D
[2021-10-05 09:22:15] I cognit | COGNITO self.domain: m1.ogoro.me
[2021-10-05 09:22:15] I cognit | COGNITO self.aws_nlb: m1-core-nlb-d1a3c13eaba292ca.elb.us-east-1.amazonaws.com
[2021-10-05 09:22:15] I cognit | COGNITO initiated: <core.cognito.Users object at 0x7f6db8a75410>
[2021-10-05 09:22:15] I facebo | FB self.domain: m1.ogoro.me
[2021-10-05 09:22:15] I facebo | FB self.aws_nlb: m1-core-nlb-d1a3c13eaba292ca.elb.us-east-1.amazonaws.com
[2021-10-05 09:22:15] I facebo | FB initiated: <core.facebook.FB object at 0x7f6db903e910>
[2021-10-05 09:22:31] I engine | Traceback (most recent call last):
  File "/home/ec2-user/environment/m1/app/core-service/core/engine.py", line 127, in wrapper
    return function(self, *args, **kwargs)
  File "/home/ec2-user/environment/m1/app/core-service/core/engine.py", line 159, in queue_worker
    time.sleep(1)
  File "/home/ec2-user/environment/m1/app/core-service/core/app.py", line 64, in termination_handler
    print(f'APP termination_handler signal {signal}, {frame}')
  File "/home/ec2-user/environment/m1/app/core-service/core/app.py", line 64, in termination_handler
    print(f'APP termination_handler signal {signal}, {frame}')
RuntimeError: reentrant call inside <_io.BufferedWriter name='<stdout>'>

[2021-10-05 09:22:36] I dynamo | DYNAMO initiated
[2021-10-05 09:22:38] I engine | RUNNER initiated: <core.engine.Runner object at 0x7fabd0a04f50>
[2021-10-05 09:22:38] I engine | RUNNER queue_worker started: 19723
[2021-10-05 09:22:38] I engine | RUNNER started: <core.engine.Runner object at 0x7fabd0a04f50>
[2021-10-05 09:22:38] I telegr | BOT initiated: <core.telegram.Bot object at 0x7fabcf907810>
[2021-10-05 09:22:38] I telegr | BOT polling: <core.telegram.Bot object at 0x7fabcf907810>
[2021-10-05 09:22:38] I telegr | BOT enumerate_threads: [<_MainThread(MainThread, started 140376770172736)>, <Thread(QueueManagerThread, started daemon 140375897417472)>, <Thread(Telegram bot polling, started daemon 140375880632064)>, <Thread(QueueFeederThread, initial daemon)>]
[2021-10-05 09:22:38] I cognit | COGNITO self.client_id: 27k0oc5jiv5m28l2ldre8c79f3
[2021-10-05 09:22:38] I cognit | COGNITO self.user_pool_id: us-east-1_Vzc2ve15D
[2021-10-05 09:22:38] I cognit | COGNITO self.domain: m1.ogoro.me
[2021-10-05 09:22:38] I cognit | COGNITO self.aws_nlb: m1-core-nlb-d1a3c13eaba292ca.elb.us-east-1.amazonaws.com
[2021-10-05 09:22:38] I cognit | COGNITO initiated: <core.cognito.Users object at 0x7fabcf812190>
[2021-10-05 09:22:38] I facebo | FB self.domain: m1.ogoro.me
[2021-10-05 09:22:38] I facebo | FB self.aws_nlb: m1-core-nlb-d1a3c13eaba292ca.elb.us-east-1.amazonaws.com
[2021-10-05 09:22:38] I facebo | FB initiated: <core.facebook.FB object at 0x7fabcf8121d0>
[2021-10-05 09:22:41] I dynamo | DYNAMO initiated
[2021-10-05 09:22:43] I engine | RUNNER initiated: <core.engine.Runner object at 0x7f4cd22fcb10>
[2021-10-05 09:22:43] I engine | RUNNER started: <core.engine.Runner object at 0x7f4cd22fcb10>
[2021-10-05 09:22:43] I telegr | BOT initiated: <core.telegram.Bot object at 0x7f4cd0becbd0>
[2021-10-05 09:22:43] I engine | RUNNER queue_worker started: 19739
[2021-10-05 09:22:43] I telegr | BOT polling: <core.telegram.Bot object at 0x7f4cd0becbd0>
[2021-10-05 09:22:43] I telegr | BOT enumerate_threads: [<_MainThread(MainThread, started 139968768747328)>, <Thread(QueueManagerThread, started daemon 139967895918336)>, <Thread(Telegram bot polling, started daemon 139967808399104)>, <Thread(QueueFeederThread, initial daemon)>]
[2021-10-05 09:22:43] I cognit | COGNITO self.client_id: 27k0oc5jiv5m28l2ldre8c79f3
[2021-10-05 09:22:43] I cognit | COGNITO self.user_pool_id: us-east-1_Vzc2ve15D
[2021-10-05 09:22:43] I cognit | COGNITO self.domain: m1.ogoro.me
[2021-10-05 09:22:43] I cognit | COGNITO self.aws_nlb: m1-core-nlb-d1a3c13eaba292ca.elb.us-east-1.amazonaws.com
[2021-10-05 09:22:43] I cognit | COGNITO initiated: <core.cognito.Users object at 0x7f4cd1b0fe10>
[2021-10-05 09:22:43] I facebo | FB self.domain: m1.ogoro.me
[2021-10-05 09:22:43] I facebo | FB self.aws_nlb: m1-core-nlb-d1a3c13eaba292ca.elb.us-east-1.amazonaws.com
[2021-10-05 09:22:43] I facebo | FB initiated: <core.facebook.FB object at 0x7f4cd0b84650>
[2021-10-05 09:23:28] I dynamo | DYNAMO initiated
[2021-10-05 09:23:30] I engine | RUNNER initiated: <core.engine.Runner object at 0x7fe0f6d0e7d0>
[2021-10-05 09:23:30] I engine | RUNNER started: <core.engine.Runner object at 0x7fe0f6d0e7d0>
[2021-10-05 09:23:30] I telegr | BOT initiated: <core.telegram.Bot object at 0x7fe0f6c80950>
[2021-10-05 09:23:30] I engine | RUNNER queue_worker started: 20899
[2021-10-05 09:23:30] I telegr | BOT polling: <core.telegram.Bot object at 0x7fe0f6c80950>
[2021-10-05 09:23:30] I telegr | BOT enumerate_threads: [<_MainThread(MainThread, started 140605061969728)>, <Thread(QueueManagerThread, started daemon 140604189214464)>, <Thread(Telegram bot polling, started daemon 140604172429056)>, <Thread(QueueFeederThread, initial daemon)>]
[2021-10-05 09:23:30] I cognit | COGNITO self.client_id: 27k0oc5jiv5m28l2ldre8c79f3
[2021-10-05 09:23:30] I cognit | COGNITO self.user_pool_id: us-east-1_Vzc2ve15D
[2021-10-05 09:23:30] I cognit | COGNITO self.domain: m1.ogoro.me
[2021-10-05 09:23:30] I cognit | COGNITO self.aws_nlb: m1-core-nlb-d1a3c13eaba292ca.elb.us-east-1.amazonaws.com
[2021-10-05 09:23:30] I cognit | COGNITO initiated: <core.cognito.Users object at 0x7fe0f6c18350>
[2021-10-05 09:23:30] I facebo | FB self.domain: m1.ogoro.me
[2021-10-05 09:23:30] I facebo | FB self.aws_nlb: m1-core-nlb-d1a3c13eaba292ca.elb.us-east-1.amazonaws.com
[2021-10-05 09:23:30] I facebo | FB initiated: <core.facebook.FB object at 0x7fe0f6c18390>
[2021-10-05 09:23:33] I dynamo | DYNAMO initiated
[2021-10-05 09:23:35] I engine | RUNNER initiated: <core.engine.Runner object at 0x7f755849f690>
[2021-10-05 09:23:35] I engine | RUNNER started: <core.engine.Runner object at 0x7f755849f690>
[2021-10-05 09:23:35] I telegr | BOT initiated: <core.telegram.Bot object at 0x7f75580257d0>
[2021-10-05 09:23:35] I engine | RUNNER queue_worker started: 20910
[2021-10-05 09:23:35] I telegr | BOT polling: <core.telegram.Bot object at 0x7f75580257d0>
[2021-10-05 09:23:35] I telegr | BOT enumerate_threads: [<_MainThread(MainThread, started 140142836787008)>, <Thread(QueueManagerThread, started daemon 140141963958016)>, <Thread(Telegram bot polling, started daemon 140141947172608)>, <Thread(QueueFeederThread, initial daemon)>]
[2021-10-05 09:23:35] I cognit | COGNITO self.client_id: 27k0oc5jiv5m28l2ldre8c79f3
[2021-10-05 09:23:35] I cognit | COGNITO self.user_pool_id: us-east-1_Vzc2ve15D
[2021-10-05 09:23:35] I cognit | COGNITO self.domain: m1.ogoro.me
[2021-10-05 09:23:35] I cognit | COGNITO self.aws_nlb: m1-core-nlb-d1a3c13eaba292ca.elb.us-east-1.amazonaws.com
[2021-10-05 09:23:35] I cognit | COGNITO initiated: <core.cognito.Users object at 0x7f7557fbc150>
[2021-10-05 09:23:35] I facebo | FB self.domain: m1.ogoro.me
[2021-10-05 09:23:35] I facebo | FB self.aws_nlb: m1-core-nlb-d1a3c13eaba292ca.elb.us-east-1.amazonaws.com
[2021-10-05 09:23:35] I facebo | FB initiated: <core.facebook.FB object at 0x7f7557fbc190>
[2021-10-05 09:23:39] I engine | Traceback (most recent call last):
  File "/home/ec2-user/environment/m1/app/core-service/core/engine.py", line 127, in wrapper
    return function(self, *args, **kwargs)
  File "/home/ec2-user/environment/m1/app/core-service/core/engine.py", line 159, in queue_worker
    time.sleep(1)
  File "/home/ec2-user/environment/m1/app/core-service/core/app.py", line 64, in termination_handler
    print(f'APP termination_handler signal {signal}, {frame}')
OSError: [Errno 5] Input/output error

[2021-10-05 09:23:39] I engine | Traceback (most recent call last):
  File "/home/ec2-user/environment/m1/app/core-service/core/engine.py", line 127, in wrapper
    return function(self, *args, **kwargs)
  File "/home/ec2-user/environment/m1/app/core-service/core/engine.py", line 159, in queue_worker
    time.sleep(1)
  File "/home/ec2-user/environment/m1/app/core-service/core/app.py", line 64, in termination_handler
    print(f'APP termination_handler signal {signal}, {frame}')
OSError: [Errno 5] Input/output error

[2021-10-05 09:23:58] I dynamo | DYNAMO initiated
[2021-10-05 09:24:00] I engine | RUNNER initiated: <core.engine.Runner object at 0x7faaee14a750>
[2021-10-05 09:24:00] I engine | RUNNER queue_worker started: 21229
[2021-10-05 09:24:00] I engine | RUNNER started: <core.engine.Runner object at 0x7faaee14a750>
[2021-10-05 09:24:00] I telegr | BOT initiated: <core.telegram.Bot object at 0x7faaee065a10>
[2021-10-05 09:24:00] I telegr | BOT polling: <core.telegram.Bot object at 0x7faaee065a10>
[2021-10-05 09:24:00] I telegr | BOT enumerate_threads: [<_MainThread(MainThread, started 140372986816320)>, <Thread(QueueManagerThread, started daemon 140372114061056)>, <Thread(Telegram bot polling, started daemon 140372097275648)>, <Thread(QueueFeederThread, initial daemon)>]
[2021-10-05 09:24:00] I cognit | COGNITO self.client_id: 27k0oc5jiv5m28l2ldre8c79f3
[2021-10-05 09:24:00] I cognit | COGNITO self.user_pool_id: us-east-1_Vzc2ve15D
[2021-10-05 09:24:00] I cognit | COGNITO self.domain: m1.ogoro.me
[2021-10-05 09:24:00] I cognit | COGNITO self.aws_nlb: m1-core-nlb-d1a3c13eaba292ca.elb.us-east-1.amazonaws.com
[2021-10-05 09:24:00] I cognit | COGNITO initiated: <core.cognito.Users object at 0x7faaedffb3d0>
[2021-10-05 09:24:00] I facebo | FB self.domain: m1.ogoro.me
[2021-10-05 09:24:00] I facebo | FB self.aws_nlb: m1-core-nlb-d1a3c13eaba292ca.elb.us-east-1.amazonaws.com
[2021-10-05 09:24:00] I facebo | FB initiated: <core.facebook.FB object at 0x7faaedffb410>
[2021-10-05 09:24:36] I dynamo | DYNAMO initiated
[2021-10-05 09:24:39] I engine | RUNNER initiated: <core.engine.Runner object at 0x7f364e774850>
[2021-10-05 09:24:39] I engine | RUNNER queue_worker started: 21583
[2021-10-05 09:24:39] I engine | RUNNER started: <core.engine.Runner object at 0x7f364e774850>
[2021-10-05 09:24:39] I telegr | BOT initiated: <core.telegram.Bot object at 0x7f364e690dd0>
[2021-10-05 09:24:39] I telegr | BOT polling: <core.telegram.Bot object at 0x7f364e690dd0>
[2021-10-05 09:24:39] I telegr | BOT enumerate_threads: [<_MainThread(MainThread, started 139872092682048)>, <Thread(QueueManagerThread, started daemon 139871219975936)>, <Thread(Telegram bot polling, started daemon 139871203190528)>, <Thread(QueueFeederThread, initial daemon)>]
[2021-10-05 09:24:39] I cognit | COGNITO self.client_id: 27k0oc5jiv5m28l2ldre8c79f3
[2021-10-05 09:24:39] I cognit | COGNITO self.user_pool_id: us-east-1_Vzc2ve15D
[2021-10-05 09:24:39] I cognit | COGNITO self.domain: m1.ogoro.me
[2021-10-05 09:24:39] I cognit | COGNITO self.aws_nlb: m1-core-nlb-d1a3c13eaba292ca.elb.us-east-1.amazonaws.com
[2021-10-05 09:24:39] I cognit | COGNITO initiated: <core.cognito.Users object at 0x7f364e624790>
[2021-10-05 09:24:39] I facebo | FB self.domain: m1.ogoro.me
[2021-10-05 09:24:39] I facebo | FB self.aws_nlb: m1-core-nlb-d1a3c13eaba292ca.elb.us-east-1.amazonaws.com
[2021-10-05 09:24:39] I facebo | FB initiated: <core.facebook.FB object at 0x7f364e765e10>
[2021-10-05 09:24:41] I dynamo | DYNAMO initiated
[2021-10-05 09:24:43] I engine | RUNNER initiated: <core.engine.Runner object at 0x7f924b045e10>
[2021-10-05 09:24:43] I engine | RUNNER queue_worker started: 21591
[2021-10-05 09:24:43] I engine | RUNNER started: <core.engine.Runner object at 0x7f924b045e10>
[2021-10-05 09:24:43] I telegr | BOT initiated: <core.telegram.Bot object at 0x7f924aa54850>
[2021-10-05 09:24:43] I telegr | BOT polling: <core.telegram.Bot object at 0x7f924aa54850>
[2021-10-05 09:24:43] I telegr | BOT enumerate_threads: [<_MainThread(MainThread, started 140267166635840)>, <Thread(QueueManagerThread, started daemon 140266293806848)>, <Thread(Telegram bot polling, started daemon 140266277021440)>, <Thread(QueueFeederThread, initial daemon)>]
[2021-10-05 09:24:43] I cognit | COGNITO self.client_id: 27k0oc5jiv5m28l2ldre8c79f3
[2021-10-05 09:24:43] I cognit | COGNITO self.user_pool_id: us-east-1_Vzc2ve15D
[2021-10-05 09:24:43] I cognit | COGNITO self.domain: m1.ogoro.me
[2021-10-05 09:24:43] I cognit | COGNITO self.aws_nlb: m1-core-nlb-d1a3c13eaba292ca.elb.us-east-1.amazonaws.com
[2021-10-05 09:24:43] I cognit | COGNITO initiated: <core.cognito.Users object at 0x7f924a9ec210>
[2021-10-05 09:24:43] I facebo | FB self.domain: m1.ogoro.me
[2021-10-05 09:24:43] I facebo | FB self.aws_nlb: m1-core-nlb-d1a3c13eaba292ca.elb.us-east-1.amazonaws.com
[2021-10-05 09:24:43] I facebo | FB initiated: <core.facebook.FB object at 0x7f924a9ec250>
[2021-10-05 09:24:50] I engine | Traceback (most recent call last):
  File "/home/ec2-user/environment/m1/app/core-service/core/engine.py", line 127, in wrapper
    return function(self, *args, **kwargs)
  File "/home/ec2-user/environment/m1/app/core-service/core/engine.py", line 159, in queue_worker
    time.sleep(1)
  File "/home/ec2-user/environment/m1/app/core-service/core/app.py", line 64, in termination_handler
    print(f'APP termination_handler signal {signal}, {frame}')
  File "/home/ec2-user/environment/m1/app/core-service/core/app.py", line 64, in termination_handler
    print(f'APP termination_handler signal {signal}, {frame}')
RuntimeError: reentrant call inside <_io.BufferedWriter name='<stdout>'>

[2021-10-05 09:24:50] I engine | Traceback (most recent call last):
  File "/home/ec2-user/environment/m1/app/core-service/core/engine.py", line 127, in wrapper
    return function(self, *args, **kwargs)
  File "/home/ec2-user/environment/m1/app/core-service/core/engine.py", line 159, in queue_worker
    time.sleep(1)
  File "/home/ec2-user/environment/m1/app/core-service/core/app.py", line 64, in termination_handler
    print(f'APP termination_handler signal {signal}, {frame}')
  File "/home/ec2-user/environment/m1/app/core-service/core/app.py", line 64, in termination_handler
    print(f'APP termination_handler signal {signal}, {frame}')
RuntimeError: reentrant call inside <_io.BufferedWriter name='<stdout>'>

[2021-10-05 09:25:35] I dynamo | DYNAMO initiated
[2021-10-05 09:25:37] I engine | RUNNER initiated: <core.engine.Runner object at 0x7f0250bedc10>
[2021-10-05 09:25:37] I engine | RUNNER started: <core.engine.Runner object at 0x7f0250bedc10>
[2021-10-05 09:25:37] I telegr | BOT initiated: <core.telegram.Bot object at 0x7f0250b18b10>
[2021-10-05 09:25:37] I engine | RUNNER queue_worker started: 21945
[2021-10-05 09:25:37] I telegr | BOT polling: <core.telegram.Bot object at 0x7f0250b18b10>
[2021-10-05 09:25:37] I telegr | BOT enumerate_threads: [<_MainThread(MainThread, started 139648792733504)>, <Thread(QueueManagerThread, started daemon 139647919978240)>, <Thread(Telegram bot polling, started daemon 139647833335552)>, <Thread(QueueFeederThread, initial daemon)>]
[2021-10-05 09:25:37] I cognit | COGNITO self.client_id: 27k0oc5jiv5m28l2ldre8c79f3
[2021-10-05 09:25:37] I cognit | COGNITO self.user_pool_id: us-east-1_Vzc2ve15D
[2021-10-05 09:25:37] I cognit | COGNITO self.domain: m1.ogoro.me
[2021-10-05 09:25:37] I cognit | COGNITO self.aws_nlb: m1-core-nlb-d1a3c13eaba292ca.elb.us-east-1.amazonaws.com
[2021-10-05 09:25:37] I cognit | COGNITO initiated: <core.cognito.Users object at 0x7f0250aaf4d0>
[2021-10-05 09:25:37] I facebo | FB self.domain: m1.ogoro.me
[2021-10-05 09:25:37] I facebo | FB self.aws_nlb: m1-core-nlb-d1a3c13eaba292ca.elb.us-east-1.amazonaws.com
[2021-10-05 09:25:37] I facebo | FB initiated: <core.facebook.FB object at 0x7f0254f96210>
[2021-10-05 09:26:25] I dynamo | DYNAMO initiated
[2021-10-05 09:26:27] I engine | RUNNER initiated: <core.engine.Runner object at 0x7f66ef609210>
[2021-10-05 09:26:27] I engine | RUNNER started: <core.engine.Runner object at 0x7f66ef609210>
[2021-10-05 09:26:27] I telegr | BOT initiated: <core.telegram.Bot object at 0x7f66ee0f6a90>
[2021-10-05 09:26:27] I engine | RUNNER queue_worker started: 22285
[2021-10-05 09:26:27] I telegr | BOT polling: <core.telegram.Bot object at 0x7f66ee0f6a90>
[2021-10-05 09:26:27] I telegr | BOT enumerate_threads: [<_MainThread(MainThread, started 140080929638208)>, <Thread(QueueManagerThread, started daemon 140080056882944)>, <Thread(Telegram bot polling, started daemon 140080040097536)>, <Thread(QueueFeederThread, initial daemon)>]
[2021-10-05 09:26:28] I cognit | COGNITO self.client_id: 27k0oc5jiv5m28l2ldre8c79f3
[2021-10-05 09:26:28] I cognit | COGNITO self.user_pool_id: us-east-1_Vzc2ve15D
[2021-10-05 09:26:28] I cognit | COGNITO self.domain: m1.ogoro.me
[2021-10-05 09:26:28] I cognit | COGNITO self.aws_nlb: m1-core-nlb-d1a3c13eaba292ca.elb.us-east-1.amazonaws.com
[2021-10-05 09:26:28] I cognit | COGNITO initiated: <core.cognito.Users object at 0x7f66f1a41510>
[2021-10-05 09:26:28] I facebo | FB self.domain: m1.ogoro.me
[2021-10-05 09:26:28] I facebo | FB self.aws_nlb: m1-core-nlb-d1a3c13eaba292ca.elb.us-east-1.amazonaws.com
[2021-10-05 09:26:28] I facebo | FB initiated: <core.facebook.FB object at 0x7f66ee18f4d0>
[2021-10-05 09:26:30] I dynamo | DYNAMO initiated
[2021-10-05 09:26:32] I engine | RUNNER initiated: <core.engine.Runner object at 0x7f2300dfd4d0>
[2021-10-05 09:26:32] I engine | RUNNER queue_worker started: 22294
[2021-10-05 09:26:32] I engine | RUNNER started: <core.engine.Runner object at 0x7f2300dfd4d0>
[2021-10-05 09:26:32] I telegr | BOT initiated: <core.telegram.Bot object at 0x7f2300948a10>
[2021-10-05 09:26:32] I telegr | BOT polling: <core.telegram.Bot object at 0x7f2300948a10>
[2021-10-05 09:26:32] I telegr | BOT enumerate_threads: [<_MainThread(MainThread, started 139789182560064)>, <Thread(QueueManagerThread, started daemon 139788309829376)>, <Thread(Telegram bot polling, started daemon 139788225079040)>, <Thread(QueueFeederThread, initial daemon)>]
[2021-10-05 09:26:32] I cognit | COGNITO self.client_id: 27k0oc5jiv5m28l2ldre8c79f3
[2021-10-05 09:26:32] I cognit | COGNITO self.user_pool_id: us-east-1_Vzc2ve15D
[2021-10-05 09:26:32] I cognit | COGNITO self.domain: m1.ogoro.me
[2021-10-05 09:26:32] I cognit | COGNITO self.aws_nlb: m1-core-nlb-d1a3c13eaba292ca.elb.us-east-1.amazonaws.com
[2021-10-05 09:26:32] I cognit | COGNITO initiated: <core.cognito.Users object at 0x7f23008e1410>
[2021-10-05 09:26:32] I facebo | FB self.domain: m1.ogoro.me
[2021-10-05 09:26:32] I facebo | FB self.aws_nlb: m1-core-nlb-d1a3c13eaba292ca.elb.us-east-1.amazonaws.com
[2021-10-05 09:26:32] I facebo | FB initiated: <core.facebook.FB object at 0x7f23008e1450>
[2021-10-05 09:29:24] I engine | Traceback (most recent call last):
  File "/home/ec2-user/environment/m1/app/core-service/core/engine.py", line 127, in wrapper
    return function(self, *args, **kwargs)
  File "/home/ec2-user/environment/m1/app/core-service/core/engine.py", line 159, in queue_worker
    time.sleep(1)
  File "/home/ec2-user/environment/m1/app/core-service/core/app.py", line 69, in termination_handler
  File "/home/ec2-user/environment/m1/app/core-service/core/app.py", line 69, in termination_handler
RuntimeError: reentrant call inside <_io.BufferedWriter name='<stdout>'>

[2021-10-05 09:29:24] I engine | Traceback (most recent call last):
  File "/home/ec2-user/environment/m1/app/core-service/core/engine.py", line 127, in wrapper
    return function(self, *args, **kwargs)
  File "/home/ec2-user/environment/m1/app/core-service/core/engine.py", line 159, in queue_worker
    time.sleep(1)
  File "/home/ec2-user/environment/m1/app/core-service/core/app.py", line 69, in termination_handler
  File "/home/ec2-user/environment/m1/app/core-service/core/app.py", line 69, in termination_handler
RuntimeError: reentrant call inside <_io.BufferedWriter name='<stdout>'>

[2021-10-05 09:29:29] I dynamo | DYNAMO initiated
[2021-10-05 09:29:31] I engine | RUNNER initiated: <core.engine.Runner object at 0x7f86de1ce590>
[2021-10-05 09:29:31] I engine | RUNNER queue_worker started: 22719
[2021-10-05 09:29:31] I engine | RUNNER started: <core.engine.Runner object at 0x7f86de1ce590>
[2021-10-05 09:29:31] I telegr | BOT initiated: <core.telegram.Bot object at 0x7f86de0e9cd0>
[2021-10-05 09:29:31] I telegr | BOT polling: <core.telegram.Bot object at 0x7f86de0e9cd0>
[2021-10-05 09:29:31] I telegr | BOT enumerate_threads: [<_MainThread(MainThread, started 140218100102976)>, <Thread(QueueManagerThread, started daemon 140217227347712)>, <Thread(Telegram bot polling, started daemon 140217210562304)>, <Thread(QueueFeederThread, initial daemon)>]
[2021-10-05 09:29:31] I cognit | COGNITO self.client_id: 27k0oc5jiv5m28l2ldre8c79f3
[2021-10-05 09:29:31] I cognit | COGNITO self.user_pool_id: us-east-1_Vzc2ve15D
[2021-10-05 09:29:31] I cognit | COGNITO self.domain: m1.ogoro.me
[2021-10-05 09:29:31] I cognit | COGNITO self.aws_nlb: m1-core-nlb-d1a3c13eaba292ca.elb.us-east-1.amazonaws.com
[2021-10-05 09:29:31] I cognit | COGNITO initiated: <core.cognito.Users object at 0x7f86de07f690>
[2021-10-05 09:29:31] I facebo | FB self.domain: m1.ogoro.me
[2021-10-05 09:29:31] I facebo | FB self.aws_nlb: m1-core-nlb-d1a3c13eaba292ca.elb.us-east-1.amazonaws.com
[2021-10-05 09:29:31] I facebo | FB initiated: <core.facebook.FB object at 0x7f86de07f6d0>
[2021-10-05 09:29:34] I dynamo | DYNAMO initiated
[2021-10-05 09:29:36] I engine | RUNNER initiated: <core.engine.Runner object at 0x7f463808e650>
[2021-10-05 09:29:36] I engine | RUNNER queue_worker started: 22726
[2021-10-05 09:29:36] I engine | RUNNER started: <core.engine.Runner object at 0x7f463808e650>
[2021-10-05 09:29:36] I telegr | BOT initiated: <core.telegram.Bot object at 0x7f4636c11b50>
[2021-10-05 09:29:36] I telegr | BOT polling: <core.telegram.Bot object at 0x7f4636c11b50>
[2021-10-05 09:29:36] I telegr | BOT enumerate_threads: [<_MainThread(MainThread, started 139940415326016)>, <Thread(QueueManagerThread, started daemon 139939542570752)>, <Thread(Telegram bot polling, started daemon 139939525785344)>, <Thread(QueueFeederThread, initial daemon)>]
[2021-10-05 09:29:36] I cognit | COGNITO self.client_id: 27k0oc5jiv5m28l2ldre8c79f3
[2021-10-05 09:29:36] I cognit | COGNITO self.user_pool_id: us-east-1_Vzc2ve15D
[2021-10-05 09:29:36] I cognit | COGNITO self.domain: m1.ogoro.me
[2021-10-05 09:29:36] I cognit | COGNITO self.aws_nlb: m1-core-nlb-d1a3c13eaba292ca.elb.us-east-1.amazonaws.com
[2021-10-05 09:29:36] I cognit | COGNITO initiated: <core.cognito.Users object at 0x7f4636ba8510>
[2021-10-05 09:29:36] I facebo | FB self.domain: m1.ogoro.me
[2021-10-05 09:29:36] I facebo | FB self.aws_nlb: m1-core-nlb-d1a3c13eaba292ca.elb.us-east-1.amazonaws.com
[2021-10-05 09:29:36] I facebo | FB initiated: <core.facebook.FB object at 0x7f4636ba8550>
[2021-10-05 09:31:00] I engine | Traceback (most recent call last):
  File "/home/ec2-user/environment/m1/app/core-service/core/engine.py", line 127, in wrapper
    return function(self, *args, **kwargs)
  File "/home/ec2-user/environment/m1/app/core-service/core/engine.py", line 159, in queue_worker
    time.sleep(1)
  File "/home/ec2-user/environment/m1/app/core-service/core/app.py", line 72, in termination_handler
    config.clear_figures_folder(self)
  File "/home/ec2-user/environment/m1/app/core-service/core/app.py", line 72, in termination_handler
    config.clear_figures_folder(self)
RuntimeError: reentrant call inside <_io.BufferedWriter name='<stdout>'>

[2021-10-05 09:31:00] I engine | Traceback (most recent call last):
  File "/home/ec2-user/environment/m1/app/core-service/core/engine.py", line 127, in wrapper
    return function(self, *args, **kwargs)
  File "/home/ec2-user/environment/m1/app/core-service/core/engine.py", line 159, in queue_worker
    time.sleep(1)
  File "/home/ec2-user/environment/m1/app/core-service/core/app.py", line 72, in termination_handler
    config.clear_figures_folder(self)
  File "/home/ec2-user/environment/m1/app/core-service/core/app.py", line 72, in termination_handler
    config.clear_figures_folder(self)
RuntimeError: reentrant call inside <_io.BufferedWriter name='<stdout>'>

[2021-10-05 09:31:05] I dynamo | DYNAMO initiated
[2021-10-05 09:31:07] I engine | RUNNER initiated: <core.engine.Runner object at 0x7f498a54a0d0>
[2021-10-05 09:31:07] I engine | RUNNER started: <core.engine.Runner object at 0x7f498a54a0d0>
[2021-10-05 09:31:07] I telegr | BOT initiated: <core.telegram.Bot object at 0x7f498a2fbb10>
[2021-10-05 09:31:07] I engine | RUNNER queue_worker started: 23142
[2021-10-05 09:31:07] I telegr | BOT polling: <core.telegram.Bot object at 0x7f498a2fbb10>
[2021-10-05 09:31:07] I telegr | BOT enumerate_threads: [<_MainThread(MainThread, started 139954699982656)>, <Thread(QueueManagerThread, started daemon 139953827227392)>, <Thread(Telegram bot polling, started daemon 139953810441984)>, <Thread(QueueFeederThread, initial daemon)>]
[2021-10-05 09:31:07] I cognit | COGNITO self.client_id: 27k0oc5jiv5m28l2ldre8c79f3
[2021-10-05 09:31:07] I cognit | COGNITO self.user_pool_id: us-east-1_Vzc2ve15D
[2021-10-05 09:31:07] I cognit | COGNITO self.domain: m1.ogoro.me
[2021-10-05 09:31:07] I cognit | COGNITO self.aws_nlb: m1-core-nlb-d1a3c13eaba292ca.elb.us-east-1.amazonaws.com
[2021-10-05 09:31:07] I cognit | COGNITO initiated: <core.cognito.Users object at 0x7f498b21e8d0>
[2021-10-05 09:31:07] I facebo | FB self.domain: m1.ogoro.me
[2021-10-05 09:31:07] I facebo | FB self.aws_nlb: m1-core-nlb-d1a3c13eaba292ca.elb.us-east-1.amazonaws.com
[2021-10-05 09:31:07] I facebo | FB initiated: <core.facebook.FB object at 0x7f498a292550>
[2021-10-05 09:31:40] I engine | Traceback (most recent call last):
  File "/home/ec2-user/environment/m1/app/core-service/core/engine.py", line 127, in wrapper
    return function(self, *args, **kwargs)
  File "/home/ec2-user/environment/m1/app/core-service/core/engine.py", line 159, in queue_worker
    time.sleep(1)
  File "/home/ec2-user/environment/m1/app/core-service/core/app.py", line 74, in termination_handler
    print(f'APP termination_handler signal {signal}, {frame}')
  File "/home/ec2-user/environment/m1/app/core-service/core/app.py", line 74, in termination_handler
    print(f'APP termination_handler signal {signal}, {frame}')
RuntimeError: reentrant call inside <_io.BufferedWriter name='<stdout>'>

[2021-10-05 09:31:45] I dynamo | DYNAMO initiated
[2021-10-05 09:31:48] I engine | RUNNER initiated: <core.engine.Runner object at 0x7fd8860eff10>
[2021-10-05 09:31:48] I engine | RUNNER started: <core.engine.Runner object at 0x7fd8860eff10>
[2021-10-05 09:31:48] I telegr | BOT initiated: <core.telegram.Bot object at 0x7fd885af7e10>
[2021-10-05 09:31:48] I engine | RUNNER queue_worker started: 23460
[2021-10-05 09:31:48] I telegr | BOT polling: <core.telegram.Bot object at 0x7fd885af7e10>
[2021-10-05 09:31:48] I telegr | BOT enumerate_threads: [<_MainThread(MainThread, started 140568804788032)>, <Thread(QueueManagerThread, started daemon 140567932032768)>, <Thread(Telegram bot polling, started daemon 140567915247360)>, <Thread(QueueFeederThread, initial daemon)>]
[2021-10-05 09:31:48] I cognit | COGNITO self.client_id: 27k0oc5jiv5m28l2ldre8c79f3
[2021-10-05 09:31:48] I cognit | COGNITO self.user_pool_id: us-east-1_Vzc2ve15D
[2021-10-05 09:31:48] I cognit | COGNITO self.domain: m1.ogoro.me
[2021-10-05 09:31:48] I cognit | COGNITO self.aws_nlb: m1-core-nlb-d1a3c13eaba292ca.elb.us-east-1.amazonaws.com
[2021-10-05 09:31:48] I cognit | COGNITO initiated: <core.cognito.Users object at 0x7fd885fa9350>
[2021-10-05 09:31:48] I facebo | FB self.domain: m1.ogoro.me
[2021-10-05 09:31:48] I facebo | FB self.aws_nlb: m1-core-nlb-d1a3c13eaba292ca.elb.us-east-1.amazonaws.com
[2021-10-05 09:31:48] I facebo | FB initiated: <core.facebook.FB object at 0x7fd885a8a810>
[2021-10-05 09:31:50] I dynamo | DYNAMO initiated
[2021-10-05 09:31:52] I engine | RUNNER initiated: <core.engine.Runner object at 0x7feae7561610>
[2021-10-05 09:31:52] I engine | RUNNER queue_worker started: 23467
[2021-10-05 09:31:52] I engine | RUNNER started: <core.engine.Runner object at 0x7feae7561610>
[2021-10-05 09:31:52] I telegr | BOT initiated: <core.telegram.Bot object at 0x7feae709f990>
[2021-10-05 09:31:52] I telegr | BOT polling: <core.telegram.Bot object at 0x7feae709f990>
[2021-10-05 09:31:52] I telegr | BOT enumerate_threads: [<_MainThread(MainThread, started 140647747594048)>, <Thread(QueueManagerThread, started daemon 140646874765056)>, <Thread(Telegram bot polling, started daemon 140646857979648)>, <Thread(QueueFeederThread, initial daemon)>]
[2021-10-05 09:31:52] I cognit | COGNITO self.client_id: 27k0oc5jiv5m28l2ldre8c79f3
[2021-10-05 09:31:52] I cognit | COGNITO self.user_pool_id: us-east-1_Vzc2ve15D
[2021-10-05 09:31:52] I cognit | COGNITO self.domain: m1.ogoro.me
[2021-10-05 09:31:52] I cognit | COGNITO self.aws_nlb: m1-core-nlb-d1a3c13eaba292ca.elb.us-east-1.amazonaws.com
[2021-10-05 09:31:52] I cognit | COGNITO initiated: <core.cognito.Users object at 0x7feae7690a10>
[2021-10-05 09:31:52] I facebo | FB self.domain: m1.ogoro.me
[2021-10-05 09:31:52] I facebo | FB self.aws_nlb: m1-core-nlb-d1a3c13eaba292ca.elb.us-east-1.amazonaws.com
[2021-10-05 09:31:52] I facebo | FB initiated: <core.facebook.FB object at 0x7feae7034390>
[2021-10-05 09:32:09] I engine | Traceback (most recent call last):
  File "/home/ec2-user/environment/m1/app/core-service/core/engine.py", line 127, in wrapper
    return function(self, *args, **kwargs)
  File "/home/ec2-user/environment/m1/app/core-service/core/engine.py", line 159, in queue_worker
    time.sleep(1)
  File "/home/ec2-user/environment/m1/app/core-service/core/app.py", line 74, in termination_handler
    print(f'APP termination_handler signal {signal}, {frame}')
  File "/home/ec2-user/environment/m1/app/core-service/core/app.py", line 74, in termination_handler
    print(f'APP termination_handler signal {signal}, {frame}')
RuntimeError: reentrant call inside <_io.BufferedWriter name='<stdout>'>

[2021-10-05 09:32:09] I engine | Traceback (most recent call last):
  File "/home/ec2-user/environment/m1/app/core-service/core/engine.py", line 127, in wrapper
    return function(self, *args, **kwargs)
  File "/home/ec2-user/environment/m1/app/core-service/core/engine.py", line 159, in queue_worker
    time.sleep(1)
  File "/home/ec2-user/environment/m1/app/core-service/core/app.py", line 74, in termination_handler
    print(f'APP termination_handler signal {signal}, {frame}')
  File "/home/ec2-user/environment/m1/app/core-service/core/app.py", line 74, in termination_handler
    print(f'APP termination_handler signal {signal}, {frame}')
RuntimeError: reentrant call inside <_io.BufferedWriter name='<stdout>'>

[2021-10-05 09:32:56] I dynamo | DYNAMO initiated
[2021-10-05 09:32:58] I engine | RUNNER initiated: <core.engine.Runner object at 0x7fccfda6bf90>
[2021-10-05 09:32:58] I engine | RUNNER queue_worker started: 23804
[2021-10-05 09:32:58] I engine | RUNNER started: <core.engine.Runner object at 0x7fccfda6bf90>
[2021-10-05 09:32:58] I telegr | BOT initiated: <core.telegram.Bot object at 0x7fccfc4e9dd0>
[2021-10-05 09:32:58] I telegr | BOT polling: <core.telegram.Bot object at 0x7fccfc4e9dd0>
[2021-10-05 09:32:58] I telegr | BOT enumerate_threads: [<_MainThread(MainThread, started 140519255271232)>, <Thread(QueueManagerThread, started daemon 140518382565120)>, <Thread(Telegram bot polling, started daemon 140518365779712)>, <Thread(QueueFeederThread, initial daemon)>]
[2021-10-05 09:32:58] I cognit | COGNITO self.client_id: 27k0oc5jiv5m28l2ldre8c79f3
[2021-10-05 09:32:58] I cognit | COGNITO self.user_pool_id: us-east-1_Vzc2ve15D
[2021-10-05 09:32:58] I cognit | COGNITO self.domain: m1.ogoro.me
[2021-10-05 09:32:58] I cognit | COGNITO self.aws_nlb: m1-core-nlb-d1a3c13eaba292ca.elb.us-east-1.amazonaws.com
[2021-10-05 09:32:58] I cognit | COGNITO initiated: <core.cognito.Users object at 0x7fccfc47b7d0>
[2021-10-05 09:32:58] I facebo | FB self.domain: m1.ogoro.me
[2021-10-05 09:32:58] I facebo | FB self.aws_nlb: m1-core-nlb-d1a3c13eaba292ca.elb.us-east-1.amazonaws.com
[2021-10-05 09:32:58] I facebo | FB initiated: <core.facebook.FB object at 0x7fccfc47b810>
[2021-10-05 09:33:00] I dynamo | DYNAMO initiated
[2021-10-05 09:33:02] I engine | RUNNER initiated: <core.engine.Runner object at 0x7f0868e008d0>
[2021-10-05 09:33:02] I engine | RUNNER started: <core.engine.Runner object at 0x7f0868e008d0>
[2021-10-05 09:33:02] I telegr | BOT initiated: <core.telegram.Bot object at 0x7f08654b7950>
[2021-10-05 09:33:02] I engine | RUNNER queue_worker started: 23820
[2021-10-05 09:33:02] I telegr | BOT polling: <core.telegram.Bot object at 0x7f08654b7950>
[2021-10-05 09:33:02] I telegr | BOT enumerate_threads: [<_MainThread(MainThread, started 139674908239680)>, <Thread(QueueManagerThread, started daemon 139674035410688)>, <Thread(Telegram bot polling, started daemon 139673947076352)>, <Thread(QueueFeederThread, initial daemon)>]
[2021-10-05 09:33:02] I cognit | COGNITO self.client_id: 27k0oc5jiv5m28l2ldre8c79f3
[2021-10-05 09:33:02] I cognit | COGNITO self.user_pool_id: us-east-1_Vzc2ve15D
[2021-10-05 09:33:02] I cognit | COGNITO self.domain: m1.ogoro.me
[2021-10-05 09:33:02] I cognit | COGNITO self.aws_nlb: m1-core-nlb-d1a3c13eaba292ca.elb.us-east-1.amazonaws.com
[2021-10-05 09:33:02] I cognit | COGNITO initiated: <core.cognito.Users object at 0x7f086544d310>
[2021-10-05 09:33:02] I facebo | FB self.domain: m1.ogoro.me
[2021-10-05 09:33:02] I facebo | FB self.aws_nlb: m1-core-nlb-d1a3c13eaba292ca.elb.us-east-1.amazonaws.com
[2021-10-05 09:33:02] I facebo | FB initiated: <core.facebook.FB object at 0x7f0865542690>
[2021-10-05 09:33:05] I engine | Traceback (most recent call last):
  File "/home/ec2-user/environment/m1/app/core-service/core/engine.py", line 127, in wrapper
    return function(self, *args, **kwargs)
  File "/home/ec2-user/environment/m1/app/core-service/core/engine.py", line 159, in queue_worker
    time.sleep(1)
  File "/home/ec2-user/environment/m1/app/core-service/core/app.py", line 74, in termination_handler
    print(f'APP termination_handler signal {signal}, {frame}')
  File "/home/ec2-user/environment/m1/app/core-service/core/app.py", line 74, in termination_handler
    print(f'APP termination_handler signal {signal}, {frame}')
RuntimeError: reentrant call inside <_io.BufferedWriter name='<stdout>'>

[2021-10-05 09:33:05] I engine | Traceback (most recent call last):
  File "/home/ec2-user/environment/m1/app/core-service/core/engine.py", line 127, in wrapper
    return function(self, *args, **kwargs)
  File "/home/ec2-user/environment/m1/app/core-service/core/engine.py", line 159, in queue_worker
    time.sleep(1)
  File "/home/ec2-user/environment/m1/app/core-service/core/app.py", line 74, in termination_handler
    print(f'APP termination_handler signal {signal}, {frame}')
  File "/home/ec2-user/environment/m1/app/core-service/core/app.py", line 74, in termination_handler
    print(f'APP termination_handler signal {signal}, {frame}')
RuntimeError: reentrant call inside <_io.BufferedWriter name='<stdout>'>

[2021-10-05 09:35:31] I dynamo | DYNAMO initiated
[2021-10-05 09:35:33] I engine | RUNNER initiated: <core.engine.Runner object at 0x7f410bb2d450>
[2021-10-05 09:35:33] I engine | RUNNER started: <core.engine.Runner object at 0x7f410bb2d450>
[2021-10-05 09:35:33] I telegr | BOT initiated: <core.telegram.Bot object at 0x7f410a984910>
[2021-10-05 09:35:33] I engine | RUNNER queue_worker started: 24559
[2021-10-05 09:35:33] I telegr | BOT polling: <core.telegram.Bot object at 0x7f410a984910>
[2021-10-05 09:35:33] I telegr | BOT enumerate_threads: [<_MainThread(MainThread, started 139918199609152)>, <Thread(QueueManagerThread, started daemon 139917326853888)>, <Thread(Telegram bot polling, started daemon 139917310068480)>, <Thread(QueueFeederThread, initial daemon)>]
[2021-10-05 09:35:33] I cognit | COGNITO self.client_id: 27k0oc5jiv5m28l2ldre8c79f3
[2021-10-05 09:35:33] I cognit | COGNITO self.user_pool_id: us-east-1_Vzc2ve15D
[2021-10-05 09:35:33] I cognit | COGNITO self.domain: m1.ogoro.me
[2021-10-05 09:35:33] I cognit | COGNITO self.aws_nlb: m1-core-nlb-d1a3c13eaba292ca.elb.us-east-1.amazonaws.com
[2021-10-05 09:35:33] I cognit | COGNITO initiated: <core.cognito.Users object at 0x7f410a918310>
[2021-10-05 09:35:33] I facebo | FB self.domain: m1.ogoro.me
[2021-10-05 09:35:33] I facebo | FB self.aws_nlb: m1-core-nlb-d1a3c13eaba292ca.elb.us-east-1.amazonaws.com
[2021-10-05 09:35:33] I facebo | FB initiated: <core.facebook.FB object at 0x7f410a918350>
[2021-10-05 09:41:48] I engine | Traceback (most recent call last):
  File "/home/ec2-user/environment/m1/app/core-service/core/engine.py", line 127, in wrapper
    return function(self, *args, **kwargs)
  File "/home/ec2-user/environment/m1/app/core-service/core/engine.py", line 159, in queue_worker
    time.sleep(1)
  File "/home/ec2-user/environment/m1/app/core-service/core/app.py", line 71, in termination_handler
    print(f'APP termination_handler signal {signal}, {frame}')
  File "/home/ec2-user/environment/m1/app/core-service/core/app.py", line 71, in termination_handler
    print(f'APP termination_handler signal {signal}, {frame}')
RuntimeError: reentrant call inside <_io.BufferedWriter name='<stdout>'>

[2021-10-05 09:42:49] I dynamo | DYNAMO initiated
[2021-10-05 09:42:51] I engine | RUNNER initiated: <core.engine.Runner object at 0x7f8f17e79050>
[2021-10-05 09:42:51] I engine | RUNNER queue_worker started: 25482
[2021-10-05 09:42:51] I engine | RUNNER started: <core.engine.Runner object at 0x7f8f17e79050>
[2021-10-05 09:42:51] I telegr | BOT initiated: <core.telegram.Bot object at 0x7f8f17d79c10>
[2021-10-05 09:42:51] I telegr | BOT polling: <core.telegram.Bot object at 0x7f8f17d79c10>
[2021-10-05 09:42:51] I telegr | BOT enumerate_threads: [<_MainThread(MainThread, started 140253429577536)>, <Thread(QueueManagerThread, started daemon 140252556560128)>, <Thread(Telegram bot polling, started daemon 140252539774720)>, <Thread(QueueFeederThread, initial daemon)>]
[2021-10-05 09:42:51] I cognit | COGNITO self.client_id: 27k0oc5jiv5m28l2ldre8c79f3
[2021-10-05 09:42:51] I cognit | COGNITO self.user_pool_id: us-east-1_Vzc2ve15D
[2021-10-05 09:42:51] I cognit | COGNITO self.domain: m1.ogoro.me
[2021-10-05 09:42:51] I cognit | COGNITO self.aws_nlb: m1-core-nlb-d1a3c13eaba292ca.elb.us-east-1.amazonaws.com
[2021-10-05 09:42:51] I cognit | COGNITO initiated: <core.cognito.Users object at 0x7f8f17d105d0>
